gmath_matrix.o: gmath_matrix.c gutil.h gmath_matrix.h gmatrix.h
gmath_vector.o: gmath_vector.c gutil.h gmath_matrix.h gvector.h
gstruct.o: gstruct.c gutil.h gstruct.h gstruct_aatree.h
gutil_alloc.o: gutil_alloc.c gutil.h galloc.h
gutil_error.o: gutil_error.c gutil.h
gutil_parse.o: gutil_parse.c gutil.h
rtutil_math.o: rtutil_math.c rtutil_math.h
rtutil_scat_io.o: rtutil_scat_io.c rtutil_scat_io.h rtutil_size_dist.h \
 rtutil_support.h
rtutil_size_dist.o: rtutil_size_dist.c rtutil_math.h rtutil_size_dist.h
rtutil_support.o: rtutil_support.c rtutil_size_dist.h rtutil_support.h
