gindex_name_value.o: gindex_name_value.c gutil.h gindex_name_value.h
glist.o: glist.c gutil.h glist.h
gmath_mat2d3d.o: gmath_mat2d3d.c gutil.h gmath.h
gmath_matrix.o: gmath_matrix.c gutil.h gmath_matrix.h gmatrix.h
gmath_vector.o: gmath_vector.c gutil.h gmath_matrix.h gvector.h
gstruct.o: gstruct.c gutil.h gstruct.h gstruct_aatree.h gstruct_dclist.h
gutil_alloc.o: gutil_alloc.c gutil.h galloc.h
gutil_cmp.o: gutil_cmp.c gutil.h
gutil_error.o: gutil_error.c gutil.h
gutil_parse.o: gutil_parse.c gutil.h
gutil_sort.o: gutil_sort.c gutil.h
gutil_string.o: gutil_string.c gutil.h
rtutil_math.o: rtutil_math.c rtutil_math.h
rtutil_scat_fft.o: rtutil_scat_fft.c rtutil_scat_fft.h
rtutil_scat_io.o: rtutil_scat_io.c rtutil_scat_io.h rtutil_size_dist.h \
 rtutil_support.h
rtutil_size_dist.o: rtutil_size_dist.c rtutil_math.h rtutil_size_dist.h \
 zeroin.h
rtutil_support.o: rtutil_support.c rtutil_size_dist.h rtutil_support.h
zeroin.o: zeroin.c zeroin.h
