/* xrtm_matrix.c */
void dvec_scale_add(double *a, double *b, double *c, double alpha, long n);
void dmat_scale_trans(double **a, double **b, double alpha, long m, long n);
void dmat_scale_add(double **a, double **b, double **c, double alpha, long m, long n);
double dmat_p_one_norm_A(double **r, double **t, long n);
double dmat_p_inf_norm_A(double **r, double **t, long n);
double dmat_frob_norm_A(double **r, double **t, long n);
int positive_definite(double **a, int n);
void dmat_sym(double **a, long m, double alpha);
void dsym_add(double **a, double **b, double **c, long m, int flag);
void dsym_sub(double **a, double **b, double **c, long m, int flag);
void dsym_mul_kernel(double **a, double **b, double alpha, long m, long o, double **c, double beta, int flag, int thresh);
void dsym_mul(double **a, double **b, long m, long o, double **c, int flag);
void dsym_mma(double **a1, double **b1, double **a2, double **b2, long m, long o, double **c, int flag);
void dsym_mms(double **a1, double **b1, double **a2, double **b2, long m, long o, double **c, int flag);
void dsym_m_a(double **a1, double **b1, double **a2, long m, long o, double **c, int flag);
void dsym_m_s(double **a1, double **b1, double **a2, long m, long o, double **c, int flag);
void dsym_mta(double **a, double **b, long m, long o, double **c);
void dsym_mts(double **a, double **b, long m, long o, double **c);
void zmat_real(dcomplex **z, double **d, long m, long n);
void zmat_imag(dcomplex **z, double **d, long m, long n);
void dmat_complex(double **dr, double **di, dcomplex **z, long m, long n);
void dmat_complex2(double **dr, double **di, double alpha, dcomplex **z, double beta, long m, long n);
void dzmat_diag_mul(double *a, dcomplex **b, dcomplex **c, long m, long n);
void dzmat_mul(double **a, dcomplex **b, long m, long n, long o, dcomplex **c);
void dzmat_mul2(double **a, dcomplex **b, long m, long n, long o, dcomplex **c, double **don, double **dmn1, double **dmn2);
void dzmat_gxgxmx(int trans_a, double **a, int trans_b, dcomplex **b, double alpha, dcomplex **c, double beta, long m, long n, long o, double **don, double **dmn1, double **dmn2);
void insert_vector1_d(int n, int i, double *a, double alpha, double *b);
void insert_matrix1_d(int m, int n, int i, int j, double **a, double alpha, double **b);
void insert_matrix2_d(int m, int n, int i, int j, double **a, double alpha, double *d, double **b);
void insert_vector1_dc(int n, int i, dcomplex *a, dcomplex alpha, dcomplex *b);
void insert_matrix1_dc(int m, int n, int i, int j, dcomplex **a, dcomplex alpha, dcomplex **b);
void insert_matrix2_dc(int m, int n, int i, int j, dcomplex **a, dcomplex alpha, dcomplex *d, dcomplex **b);
void insert_matrix_band_storage1_d(int m, int n, int kl, int ku, int i1, int j1, double **a, double alpha, double **b);
void insert_matrix_band_storage2_d(int m, int n, int kl, int ku, int i1, int j1, double **a, double alpha, double *d, double **b);
void insert_matrix_band_storage1_dc(int m, int n, int kl, int ku, int i1, int j1, dcomplex **a, dcomplex alpha, dcomplex **b);
void insert_matrix_band_storage2_dc(int m, int n, int kl, int ku, int i1, int j1, dcomplex **a, dcomplex alpha, dcomplex *d, dcomplex **b);
void dmat_dtutumx(double **a, double **b, double **c, long n);
void dmat_dtutlmx(double **a, double **b, double **c, long n);
void dmat_dtltumx(double **a, double **b, double **c, long n);
void dmat_dgxtumx(double **a, double **b, double **c, long n);
void dmat_dgxtlmx(double **a, double **b, double **c, long n);
void dmat_dtugxmx(double **a, double **b, double **c, long n);
void dmat_dtlgxmx(double **a, double **b, double **c, long n);
void dmat_dtutlms(double **a, double **b, double **c, int n, int flag);
void dmat_dtltums(double **a, double **b, double **c, int n, int flag);
void dmat_dgxtums(double **a, double **b, double **c, int n, int flag);
void dmat_dgxtlms(double **a, double **b, double **c, int n, int flag);
void dmat_dtugxms(double **a, double **b, double **c, int n, int flag);
void dmat_dtlgxms(double **a, double **b, double **c, int n, int flag);
void dmat_dtugxtlms(double **a, double **b, double **c, double **d, double **w, int n);
void dmat_dtugxtlms_l(double **a, double **b, double **c, double **d, double **e, double **f, double **g, double **h, double **w1, int n);
void dmat_chol(double **a, long n);
void dmat_chol_l(double **a, double **b, long n);
void dmat_mul_brow(double **ax1, double **ax2, double **b11, double **b12, double **b21, double **b22, long n, double **cx1, double **cx2);
void dmat_mul_bcol(double **a11, double **a12, double **a21, double **a22, double **b1x, double **b2x, long n, double **c1x, double **c2x);
void dmat_copy_1x2(double **b11, double **b12, double **a11, double **a12, int n);
void dmat_copy_2x2(double **b11, double **b12, double **b21, double **b22, double **a11, double **a12, double **a21, double **a22, int n);
void dmat_init_1x2(double **a11, double **a12, double alpha, int n);
void dmat_init_2x2(double **a11, double **a12, double **a21, double **a22, double alpha, int n);
void dmat_scale_add_1x2(double **a11, double **a12, double **b11, double **b12, double **P11, double **P12, double alpha, int n);
void dmat_scale_add_2x2(double **a11, double **a12, double **a21, double **a22, double **b11, double **b12, double **b21, double **b22, double **P11, double **P12, double **P21, double **P22, double alpha, int n);
void dmat_mul_2x2(double **a11, double **a12, double **a21, double **a22, double **b11, double **b12, double **b21, double **b22, long n, double **P11, double **P12, double **P21, double **P22);
