/* xrtm_matrix.c */
void dvec_scale_add(double *a, double *b, double *c, double alpha, long n);
void dmat_scale_trans(double **a, double **b, double alpha, long m, long n);
void dmat_scale_add(double **a, double **b, double **c, double alpha, long m, long n);
double dmat_p_one_norm_A(double **r, double **t, long n);
double dmat_p_inf_norm_A(double **r, double **t, long n);
double dmat_frob_norm_A(double **r, double **t, long n);
int positive_definite(double **a, int n);
void dmat_sym(double **a, long m, double alpha);
void dsym_add(double **a, double **b, double **c, long m, int flag);
void dsym_sub(double **a, double **b, double **c, long m, int flag);
void dsym_mul_kernel(double **a, double **b, double alpha, long m, long o, double **c, double beta, int flag, int thresh);
void dsym_mul(double **a, double **b, long m, long o, double **c, int flag);
void dsym_mma(double **a1, double **b1, double **a2, double **b2, long m, long o, double **c, int flag);
void dsym_mms(double **a1, double **b1, double **a2, double **b2, long m, long o, double **c, int flag);
void dsym_m_a(double **a1, double **b1, double **a2, long m, long o, double **c, int flag);
void dsym_m_s(double **a1, double **b1, double **a2, long m, long o, double **c, int flag);
void dsym_mta(double **a, double **b, long m, long o, double **c);
void dsym_mts(double **a, double **b, long m, long o, double **c);
void zmat_real(dcomplex **z, double **d, long m, long n);
void zmat_imag(dcomplex **z, double **d, long m, long n);
void dmat_complex(double **dr, double **di, dcomplex **z, long m, long n);
void dmat_complex2(double **dr, double **di, double alpha, dcomplex **z, double beta, long m, long n);
void dzmat_diag_mul(double *a, dcomplex **b, dcomplex **c, long m, long n);
void dzmat_mul(double **a, dcomplex **b, long m, long n, long o, dcomplex **c);
void dzmat_mul2(double **a, dcomplex **b, long m, long n, long o, dcomplex **c, double **don, double **dmn1, double **dmn2);
void dzmat_gxgxmx(int trans_a, double **a, int trans_b, dcomplex **b, double alpha, dcomplex **c, double beta, long m, long n, long o, double **don, double **dmn1, double **dmn2);
void insert_vector1_d(int n, int i, double *a, double alpha, double *b);
void insert_matrix1_d(int m, int n, int i, int j, double **a, double alpha, double **b);
void insert_matrix2_d(int m, int n, int i, int j, double **a, double alpha, double *d, double **b);
void insert_vector1_dc(int n, int i, dcomplex *a, dcomplex alpha, dcomplex *b);
void insert_matrix1_dc(int m, int n, int i, int j, dcomplex **a, dcomplex alpha, dcomplex **b);
void insert_matrix2_dc(int m, int n, int i, int j, dcomplex **a, dcomplex alpha, dcomplex *d, dcomplex **b);
void insert_matrix_band_storage1_d(int m, int n, int kl, int ku, int i1, int j1, double **a, double alpha, double **b);
void insert_matrix_band_storage2_d(int m, int n, int kl, int ku, int i1, int j1, double **a, double alpha, double *d, double **b);
void insert_matrix_band_storage1_dc(int m, int n, int kl, int ku, int i1, int j1, dcomplex **a, dcomplex alpha, dcomplex **b);
void insert_matrix_band_storage2_dc(int m, int n, int kl, int ku, int i1, int j1, dcomplex **a, dcomplex alpha, dcomplex *d, dcomplex **b);
