/* xrtm_adding.c */
int layer_add_aux_alloc(layer_add_aux_data *d, int n);
void layer_add_aux_free(layer_add_aux_data *d);
void layer_zero_ref(double **R_m, double *S_p, int n);
void layer_zero_ref_l(double **R_m, double *S_p, double ***R_m_l, double **S_p_l, int n, int n_derivs, uchar *derivs_layers, uchar *derivs_sources);
void layer_copy_ref(double **R_m2, double *S_p2, double **R_m1, double *S_p1, int n);
void layer_copy_ref_l(double **R_m2, double *S_p2, double **R_m1, double *S_p1, double ***R_m_l2, double **S_p_l2, double ***R_m_l1, double **S_p_l1, int n, int n_derivs, uchar *derivs_layers, uchar *derivs_sources);
void layer_add_ref(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double *S32, double **R13, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double **S32_l, double ***R13_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, int flag2, save_tree_data save_tree, work_data work);
void layer_add_ref2(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double *S32, double **R13, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double **S32_l, double ***R13_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, int flag2, int flag3, work_data work, layer_add_aux_data *d);
void layer_zero_all(double **R_m, double **T_m, double *S_m, double **R_p, double **T_p, double *S_p, int n);
void layer_zero_all_l(double **R_m, double **T_m, double *S_m, double **R_p, double **T_p, double *S_p, double ***R_m_l, double ***T_m_l, double **S_m_l, double ***R_p_l, double ***T_p_l, double **S_p_l, int n, int n_derivs, uchar *derivs);
void layer_copy_all(double **R_m2, double **T_m2, double *S_m2, double **R_p2, double **T_p2, double *S_p2, double **R_m1, double **T_m1, double *S_m1, double **R_p1, double **T_p1, double *S_p1, int n);
void layer_copy_all_l(double **R_m2, double **T_m2, double *S_m2, double **R_p2, double **T_p2, double *S_p2, double **R_m1, double **T_m1, double *S_m1, double **R_p1, double **T_p1, double *S_p1, double ***R_m_l2, double ***T_m_l2, double **S_m_l2, double ***R_p_l2, double ***T_p_l2, double **S_p_l2, double ***R_m_l1, double ***T_m_l1, double **S_m_l1, double ***R_p_l1, double ***T_p_l1, double **S_p_l1, int n, int n_derivs, uchar *derivs);
void source_add_all(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double **T23, double *S23, double **R32, double **T32, double *S32, double **R13, double **T13, double *S13, double **R31, double **T31, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double ***T23_l, double **S23_l, double ***R32_l, double ***T32_l, double **S32_l, double ***R13_l, double ***T13_l, double **S13_l, double ***R31_l, double ***T31_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, work_data work);
void layer_add_all(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double **T23, double *S23, double **R32, double **T32, double *S32, double **R13, double **T13, double *S13, double **R31, double **T31, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double ***T23_l, double **S23_l, double ***R32_l, double ***T32_l, double **S32_l, double ***R13_l, double ***T13_l, double **S13_l, double ***R31_l, double ***T31_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, save_tree_data save_tree, work_data work);
void source_add_all2(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double **T23, double *S23, double **R32, double **T32, double *S32, double **R13, double **T13, double *S13, double **R31, double **T31, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double ***T23_l, double **S23_l, double ***R32_l, double ***T32_l, double **S32_l, double ***R13_l, double ***T13_l, double **S13_l, double ***R31_l, double ***T31_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, int flag2, work_data work, layer_add_aux_data *d);
void layer_add_all2(double **R12, double **T12, double *S12, double **R21, double **T21, double *S21, double **R23, double **T23, double *S23, double **R32, double **T32, double *S32, double **R13, double **T13, double *S13, double **R31, double **T31, double *S31, double ***R12_l, double ***T12_l, double **S12_l, double ***R21_l, double ***T21_l, double **S21_l, double ***R23_l, double ***T23_l, double **S23_l, double ***R32_l, double ***T32_l, double **S32_l, double ***R13_l, double ***T13_l, double **S13_l, double ***R31_l, double ***T31_l, double **S31_l, int n, int n_derivs, double atran, double *atran_l, uchar *derivs, int flag, int flag2, work_data work, layer_add_aux_data *d);
