/* test_util.c */
int test_bound_n(void);
int test_bound_max_name_length(void);
const char *test_bound_index_to_name(int index);
int test_bound_name_to_index(const char *name);
enum test_bound_type test_bound_index_to_value(int index);
int test_bound_value_to_index(enum test_bound_type type);
enum test_bound_type test_bound_name_to_value(const char *name);
const char *test_bound_value_to_name(enum test_bound_type type);
int test_stack_n(void);
int test_stack_max_name_length(void);
const char *test_stack_index_to_name(int index);
int test_stack_name_to_index(const char *name);
enum test_stack_type test_stack_index_to_value(int index);
int test_stack_value_to_index(enum test_stack_type type);
enum test_stack_type test_stack_name_to_value(const char *name);
const char *test_stack_value_to_name(enum test_stack_type type);
int test_derivs_n(void);
int test_derivs_max_name_length(void);
const char *test_derivs_index_to_name(int index);
int test_derivs_name_to_index(const char *name);
enum test_derivs_type test_derivs_index_to_value(int index);
int test_derivs_value_to_index(enum test_derivs_type type);
enum test_derivs_type test_derivs_name_to_value(const char *name);
const char *test_derivs_value_to_name(enum test_derivs_type type);
int test_output_at_levels_n(void);
int test_output_at_levels_max_name_length(void);
const char *test_output_at_levels_index_to_name(int index);
int test_output_at_levels_name_to_index(const char *name);
enum test_output_at_levels_type test_output_at_levels_index_to_value(int index);
int test_output_at_levels_value_to_index(enum test_output_at_levels_type type);
enum test_output_at_levels_type test_output_at_levels_name_to_value(const char *name);
const char *test_output_at_levels_value_to_name(enum test_output_at_levels_type type);
int test_output_at_taus_n(void);
int test_output_at_taus_max_name_length(void);
const char *test_output_at_taus_index_to_name(int index);
int test_output_at_taus_name_to_index(const char *name);
enum test_output_at_taus_type test_output_at_taus_index_to_value(int index);
int test_output_at_taus_value_to_index(enum test_output_at_taus_type type);
enum test_output_at_taus_type test_output_at_taus_name_to_value(const char *name);
const char *test_output_at_taus_value_to_name(enum test_output_at_taus_type type);
int make_solvers(int solvers_mask1, int *solvers_mask2, enum xrtm_solver_mask *solvers_array2, double *tolerance, ...);
int make_solvers2(int solvers_mask1, int *solvers_mask2, enum xrtm_solver_mask *solvers_array2, double *tolerance_ref, double *tolerance_tran, ...);
int make_tolerance(double *tol, ...);
int get_callxrtm_cmd(xrtm_data *gd, misc_data *md, int n_phis, double *phis, char *s, size_t size);
