#line 2 "input_yylex.c"

#line 4 "input_yylex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[558] =
    {   0,
        0,    0,   74,   72,    1,   71,   72,   72,   72,   72,
       72,   69,   70,   70,   70,   70,   70,   38,   70,   70,
       70,   70,   70,   70,   70,   70,    1,    0,   65,    0,
       64,    0,   69,    0,    0,    0,    0,   38,    0,    0,
        0,    0,    0,    0,    0,    0,   68,    2,    3,   67,
       70,   70,   70,   70,   70,    4,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    3,   66,    0,   27,

       70,   70,   70,   70,   70,   39,   57,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   27,    0,
        0,    0,    0,    0,   39,   57,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,    0,
        0,   67,   70,   40,   70,   70,   70,   70,   70,   70,
       46,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,    0,   40,
        0,    0,    0,    0,    0,    0,   46,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   66,   70,   70,   52,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   44,   70,   70,   70,   70,   29,   70,   70,
       70,   70,   70,    0,    0,   52,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   44,
        0,    0,    0,    0,   29,    0,    0,    0,    0,    0,
       70,   70,   41,   58,   70,   70,   70,   21,   70,   47,
       61,   70,   70,   70,   70,   70,    8,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,    0,

        0,   41,   58,    0,    0,    0,   21,    0,   47,   61,
        0,    0,    0,    0,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   70,   70,
       70,   70,   70,   70,   14,   70,   70,   70,   70,   70,
       70,   70,   70,   45,   60,    5,   70,   70,   70,   70,
       70,    6,   70,   70,   28,    0,    0,    0,    0,    0,
        0,   14,    0,    0,    0,    0,    0,    0,    0,    0,
       45,   60,    5,    0,    0,    0,    0,    0,    6,    0,
        0,   28,   70,   70,   70,   70,   70,   70,   70,   34,
       23,    7,   10,   70,   11,   70,   70,    9,   70,   25,

       70,   70,   22,   70,   70,    0,    0,    0,    0,    0,
        0,    0,   34,   23,    7,   10,    0,   11,    0,    0,
        9,    0,   25,    0,    0,   22,    0,    0,   32,   30,
       70,   70,   70,   70,   70,   70,   70,   12,   70,   70,
       70,   70,   70,   70,   36,   32,   30,    0,    0,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,    0,
        0,   36,   70,   70,   42,   17,   70,   70,   70,   35,
       55,   70,   70,   70,   24,   26,   70,   19,   70,    0,
        0,   42,   17,    0,    0,    0,   35,   55,    0,    0,
        0,   24,   26,    0,   19,    0,   33,   54,   31,   53,

       70,   20,   70,   70,   70,   70,   70,   18,   37,   56,
       33,   54,   31,   53,    0,   20,    0,    0,    0,    0,
        0,   18,   37,   56,   43,   59,   70,   70,   70,   15,
       16,   43,   59,    0,    0,    0,   15,   16,   48,   49,
       13,   48,   49,   13,   70,   70,    0,    0,   50,   62,
       51,   63,   50,   62,   51,   63,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    6,    7,    1,    8,    9,   10,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   14,   14,   14,   15,   16,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,    1,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   14,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   14,   39,
       40,   41,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static const flex_int16_t yy_base[562] =
    {   0,
        0,    0,  613,  614,  610,  614,  607,  605,   33,   35,
       42,   61,    0,  592,  577,   28,   45,  590,  584,   49,
      587,  587,   45,   61,   44,  578,  600,  597,  614,  595,
      614,   72,   79,  582,  567,   56,   71,  580,  574,   75,
      577,  577,   66,   76,   68,  568,   95,  614,    0,   97,
        0,   32,  570,  563,  553,    0,  552,   23,  554,  558,
      548,  567,  545,   93,  561,  546,  545,  559,  553,  560,
       87,  543,  554,  105,  553,  546,  536,  614,  535,   68,
      537,  541,  531,  550,  528,  102,  544,  529,  528,  542,
      536,  543,   90,  526,  537,  131,    0,  129,  138,    0,

      523,  534,  520,  536,  520,    0,    0,  523,  533,  529,
      513,  532,  526,  525,  528,  508,  507,  507,  518,  515,
      523,  517,  521,  507,  498,  518,  511,  497,  614,  497,
      508,  494,  510,  494,  614,  614,  497,  507,  503,  487,
      506,  500,  499,  502,  482,  481,  481,  492,  489,  497,
      491,  495,  481,  472,  492,  485,  471,  136,  141,  147,
      145,  149,  475,  488,  486,  486,  476,  479,  479,  471,
      481,  477,  462,  461,  454,  457,  474,  460,  472,  458,
      134,  471,  476,  464,  463,  452,  465,  464,  450,  463,
      461,  461,  451,  454,  454,  446,  456,  452,  437,  436,

      429,  432,  449,  435,  447,  433,  135,  446,  451,  439,
      438,  427,  440,  439,  153,  155,  439,  104,    0,  434,
      432,  425,  434,  416,  140,  419,  423,  418,  425,  429,
      424,  417,  426,  412,  419,  151,  408,    0,  403,  404,
      419,  416,  418,  417,  150,  614,  412,  410,  403,  412,
      394,  147,  397,  401,  396,  403,  407,  402,  395,  404,
      390,  397,  156,  386,  614,  381,  382,  397,  394,  396,
      158,  386,    0,    0,  394,  376,  163,    0,  392,    0,
        0,  386,  369,  384,  371,  155,    0,  382,  156,  368,
      364,  364,  378,  381,  381,  362,  362,  373,  383,  166,

      367,  614,  614,  375,  357,  169,  614,  373,  614,  614,
      367,  350,  365,  352,  159,  614,  363,  161,  349,  345,
      345,  359,  362,  362,  343,  343,  354,  364,  343,  342,
      344,  335,  353,  174,    0,  171,  346,  333,  339,  331,
      343,  339,  328,    0,    0,    0,  340,  326,  324,  325,
      324,    0,  339,  339,    0,  324,  323,  325,  316,  334,
      178,  614,  178,  327,  314,  320,  312,  324,  320,  309,
      614,  614,  614,  321,  307,  305,  306,  305,  614,  320,
      320,  614,  300,  303,  312,  315,  296,  302,  312,  312,
        0,    0,    0,  182,    0,  290,  305,    0,  298,    0,

      307,  306,    0,  294,  303,  285,  288,  297,  300,  281,
      287,  297,  297,  614,  614,  614,  183,  614,  275,  290,
      614,  283,  614,  292,  291,  614,  279,  288,  289,  288,
      269,  266,  271,  269,  266,  173,  266,    0,  276,  261,
      261,  260,  265,  258,  275,  274,  273,  254,  251,  256,
      254,  251,  175,  251,  614,  261,  246,  246,  245,  250,
      243,  260,  181,  183,  259,    0,  247,  251,  255,    0,
        0,  235,  243,  252,    0,    0,  234,    0,  188,  193,
      194,  251,  614,  239,  243,  247,  614,  614,  227,  235,
      244,  614,  614,  226,  614,  195,    0,    0,    0,    0,

      196,    0,  242,  230,  240,  222,  221,    0,    0,    0,
      614,  614,  614,  614,  201,  614,  237,  225,  235,  217,
      216,  614,  614,  614,    0,    0,  229,  211,  222,    0,
        0,  614,  614,  220,  204,  217,  614,  614,  197,  191,
        0,  117,   96,  614,  202,  203,  204,  209,    0,    0,
        0,    0,  614,  614,  614,  614,  614,  241,  244,   77,
      247
    } ;

static const flex_int16_t yy_def[562] =
    {   0,
      557,    1,  557,  557,  557,  557,  558,  559,  557,  557,
      557,  557,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  557,  558,  557,  559,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  561,  557,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  561,  557,  557,  560,

      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,

      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  557,

      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,

      560,  560,  560,  560,  560,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  560,  560,  560,  560,

      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  560,  560,  560,  560,  560,  560,
      560,  557,  557,  557,  557,  557,  557,  557,  560,  560,
      560,  557,  557,  557,  560,  560,  557,  557,  560,  560,
      560,  560,  557,  557,  557,  557,    0,  557,  557,  557,
      557
    } ;

static const flex_int16_t yy_nxt[656] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    9,   10,   11,
       12,   12,    4,   13,   13,   14,   13,   13,   13,   15,
       16,   13,   17,   18,   13,   13,   19,   20,   21,   22,
       23,   24,   13,   13,   25,   26,   13,   13,   13,   13,
       13,   32,  100,   33,   33,   47,   47,   48,   34,   54,
      106,   49,   35,   36,  107,   37,   38,  101,   55,   39,
       40,   41,   42,   43,   44,   56,   60,   45,   46,   50,
       61,   33,   33,   65,   71,   57,   66,   76,   68,   51,
       72,   67,   47,   47,   62,   69,   77,   50,   70,   33,
       33,   78,   82,   90,   87,  135,   83,   88,   93,  136,

       91,   79,   89,   92,   94,   47,   47,   98,   98,   96,
       84,   99,  548,  113,  125,  129,   96,  154,   99,  114,
      115,  126,  142,  116,  155,  117,  272,  118,  143,  144,
      130,  273,  145,  547,  146,  274,  147,  158,  158,   98,
       98,  159,  159,  160,  161,  161,  159,  159,  162,  162,
      160,  159,  159,  215,  215,  162,  162,  216,  216,  162,
      162,  235,  262,  216,  216,  216,  216,  280,  292,  236,
      263,  281,  301,  321,  309,  293,  329,  302,  310,  334,
      322,  303,  341,  344,  356,  361,  368,  345,  371,  390,
      342,  388,  372,  330,  369,  411,  413,  335,  437,  454,

      470,  357,  487,  362,  471,  389,  488,  546,  497,  412,
      499,  391,  498,  545,  500,  509,  438,  455,  414,  510,
      511,  513,  523,  525,  512,  514,  524,  526,  532,  549,
      551,  553,  533,  550,  552,  554,  555,  544,  543,  542,
      556,   28,  541,   28,   30,  540,   30,   97,  539,   97,
      538,  537,  536,  535,  534,  531,  530,  529,  528,  527,
      522,  521,  520,  519,  518,  517,  516,  515,  508,  507,
      506,  505,  504,  503,  502,  501,  496,  495,  494,  493,
      492,  491,  490,  489,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  469,

      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  370,  367,  366,  365,  364,  363,
      360,  359,  358,  355,  354,  353,  352,  351,  350,  349,

      348,  347,  346,  343,  340,  339,  338,  337,  336,  333,
      332,  331,  328,  327,  326,  325,  324,  323,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  308,  307,
      306,  305,  304,  300,  299,  298,  297,  296,  295,  294,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      279,  278,  277,  276,  275,  271,  270,  269,  268,  267,
      266,  265,  264,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,

      222,  221,  220,  219,  218,  217,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  157,  156,
      153,  152,  151,  150,  149,  148,  141,  140,  139,  138,
      137,  134,  133,  132,  131,  128,  127,  124,  123,  122,
      121,  120,  119,  112,  111,  110,  109,  108,  105,  104,
      103,  102,   95,   86,   85,   81,   80,   75,   74,   31,

       29,   27,   73,   64,   63,   59,   58,   53,   52,   31,
       29,   27,  557,    3,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557
    } ;

static const flex_int16_t yy_chk[656] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   52,    9,    9,   10,   10,   11,    9,   16,
       58,   11,    9,    9,   58,    9,    9,   52,   16,    9,
        9,    9,    9,    9,    9,   17,   20,    9,    9,   12,
       20,   12,   12,   23,   25,   17,   23,   36,   24,  560,
       25,   23,   32,   32,   20,   24,   36,   33,   24,   33,
       33,   37,   40,   44,   43,   80,   40,   43,   45,   80,

       44,   37,   43,   44,   45,   47,   47,   50,   50,   47,
       40,   50,  543,   64,   71,   74,   47,   93,   50,   64,
       64,   71,   86,   64,   93,   64,  218,   64,   86,   86,
       74,  218,   86,  542,   86,  218,   86,   96,   96,   98,
       98,   96,   96,   98,   99,   99,  158,  158,   99,   99,
       98,  159,  159,  160,  160,  161,  161,  160,  160,  162,
      162,  181,  207,  215,  215,  216,  216,  225,  236,  181,
      207,  225,  245,  263,  252,  236,  271,  245,  252,  277,
      263,  245,  286,  289,  300,  306,  315,  289,  318,  336,
      286,  334,  318,  271,  315,  361,  363,  277,  394,  417,

      436,  300,  453,  306,  436,  334,  453,  540,  463,  361,
      464,  336,  463,  539,  464,  479,  394,  417,  363,  479,
      480,  481,  496,  501,  480,  481,  496,  501,  515,  545,
      546,  547,  515,  545,  546,  547,  548,  536,  535,  534,
      548,  558,  529,  558,  559,  528,  559,  561,  527,  561,
      521,  520,  519,  518,  517,  507,  506,  505,  504,  503,
      494,  491,  490,  489,  486,  485,  484,  482,  477,  474,
      473,  472,  469,  468,  467,  465,  462,  461,  460,  459,
      458,  457,  456,  454,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  437,  435,

      434,  433,  432,  431,  430,  429,  428,  427,  425,  424,
      422,  420,  419,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  402,  401,  399,  397,  396,  390,  389,
      388,  387,  386,  385,  384,  383,  381,  380,  378,  377,
      376,  375,  374,  370,  369,  368,  367,  366,  365,  364,
      360,  359,  358,  357,  356,  354,  353,  351,  350,  349,
      348,  347,  343,  342,  341,  340,  339,  338,  337,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  317,  314,  313,  312,  311,  308,
      305,  304,  301,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  288,  285,  284,  283,  282,  279,  276,
      275,  272,  270,  269,  268,  267,  266,  264,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  251,  250,
      249,  248,  247,  244,  243,  242,  241,  240,  239,  237,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      224,  223,  222,  221,  220,  217,  214,  213,  212,  211,
      210,  209,  208,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,

      168,  167,  166,  165,  164,  163,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  134,  133,  132,
      131,  130,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  105,  104,  103,  102,  101,   95,   94,
       92,   91,   90,   89,   88,   87,   85,   84,   83,   82,
       81,   79,   77,   76,   75,   73,   72,   70,   69,   68,
       67,   66,   65,   63,   62,   61,   60,   59,   57,   55,
       54,   53,   46,   42,   41,   39,   38,   35,   34,   30,

       28,   27,   26,   22,   21,   19,   18,   15,   14,    8,
        7,    5,    3,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557,  557,  557,  557,  557,  557,
      557,  557,  557,  557,  557
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "input_yylex.l"
/******************************************************************************%
**
**    Copyright (C) 2007-2020 Greg McGarragh <greg.mcgarragh@colostate.edu>
**
**    This source code is licensed under the GNU General Public License (GPL),
**    Version 3.  See the file COPYING for more details.
**
*******************************************************************************/
#line 11 "input_yylex.l"
#include <gutil.h>

#include "input_local.h"

void comment(locus_data *locus);
#line 787 "input_yylex.c"
#define YY_NO_UNISTD_H 1
#line 789 "input_yylex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 24 "input_yylex.l"

#line 1008 "input_yylex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 558 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 557 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "input_yylex.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "input_yylex.l"
{ comment(locus); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "input_yylex.l"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "input_yylex.l"
{ locus->statement = "fd";              return INPUT_OPTION_FD; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "input_yylex.l"
{ locus->statement = "options";         return XRTM_INPUT_OPTIONS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "input_yylex.l"
{ locus->statement = "solvers";         return XRTM_INPUT_SOLVERS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "input_yylex.l"
{ locus->statement = "max_coef";        return XRTM_INPUT_MAX_COEF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "input_yylex.l"
{ locus->statement = "n_quad";          return XRTM_INPUT_N_QUAD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "input_yylex.l"
{ locus->statement = "n_stokes";        return XRTM_INPUT_N_STOKES; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "input_yylex.l"
{ locus->statement = "n_derivs";        return XRTM_INPUT_N_DERIVS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "input_yylex.l"
{ locus->statement = "n_layers";        return XRTM_INPUT_N_LAYERS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "input_yylex.l"
{ locus->statement = "n_kernels";       return XRTM_INPUT_N_KERNELS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "input_yylex.l"
{ locus->statement = "n_kernel_quad";   return XRTM_INPUT_N_KERNEL_QUAD; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "input_yylex.l"
{ locus->statement = "kernels";         return XRTM_INPUT_KERNELS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "input_yylex.l"
{ locus->statement = "n_out_levels";    return XRTM_INPUT_N_OUT_LEVELS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "input_yylex.l"
{ locus->statement = "n_out_thetas";    return XRTM_INPUT_N_OUT_THETAS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "input_yylex.l"
{ locus->statement = "doub_d_tau";      return XRTM_INPUT_DOUB_D_TAU; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "input_yylex.l"
{ locus->statement = "pade_params";     return XRTM_INPUT_PADE_PARAMS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "input_yylex.l"
{ locus->statement = "sos_params";      return XRTM_INPUT_SOS_PARAMS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "input_yylex.l"
{ locus->statement = "fourier_tol";     return XRTM_INPUT_FOURIER_TOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "input_yylex.l"
{ locus->statement = "lambda";          return XRTM_INPUT_LAMBDA; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "input_yylex.l"
{ locus->statement = "planet_r";        return XRTM_INPUT_PLANET_R; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "input_yylex.l"
{ locus->statement = "levels_z";        return XRTM_INPUT_LEVELS_Z; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "input_yylex.l"
{ locus->statement = "out_levels";      return XRTM_INPUT_OUT_LEVELS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "input_yylex.l"
{ locus->statement = "out_taus";        return XRTM_INPUT_OUT_TAUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "input_yylex.l"
{ locus->statement = "out_thetas";      return XRTM_INPUT_OUT_THETAS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "input_yylex.l"
{ locus->statement = "F_0";             return XRTM_INPUT_F_0; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "input_yylex.l"
{ locus->statement = "theta_0";         return XRTM_INPUT_THETA_0; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "input_yylex.l"
{ locus->statement = "phi_0";           return XRTM_INPUT_PHI_0; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "input_yylex.l"
{ locus->statement = "F_iso_top";       return XRTM_INPUT_F_ISO_TOP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "input_yylex.l"
{ locus->statement = "F_iso_top_l";     return XRTM_INPUT_F_ISO_TOP_L; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "input_yylex.l"
{ locus->statement = "F_iso_bot";       return XRTM_INPUT_F_ISO_BOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "input_yylex.l"
{ locus->statement = "F_iso_bot_l";     return XRTM_INPUT_F_ISO_BOT_L; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "input_yylex.l"
{ locus->statement = "levels_b";        return XRTM_INPUT_LEVELS_B; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "input_yylex.l"
{ locus->statement = "levels_b_l";      return XRTM_INPUT_LEVELS_B_L; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "input_yylex.l"
{ locus->statement = "surface_b";       return XRTM_INPUT_SURFACE_B; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "input_yylex.l"
{ locus->statement = "surface_b-l";     return XRTM_INPUT_SURFACE_B_L; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "input_yylex.l"
{ locus->statement = "g";               return XRTM_INPUT_G; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "input_yylex.l"
{ locus->statement = "g_l";             return XRTM_INPUT_G_L; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "input_yylex.l"
{ locus->statement = "coef";            return XRTM_INPUT_CHI; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "input_yylex.l"
{ locus->statement = "coef_l";          return XRTM_INPUT_COEF_L; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "input_yylex.l"
{ locus->statement = "coef_files";      return XRTM_INPUT_COEF_FILES; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "input_yylex.l"
{ locus->statement = "coef_files_l";    return XRTM_INPUT_COEF_FILES_L; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "input_yylex.l"
{ locus->statement = "omega";           return XRTM_INPUT_OMEGA; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "input_yylex.l"
{ locus->statement = "omega_l";         return XRTM_INPUT_OMEGA_L; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "input_yylex.l"
{ locus->statement = "ltau";            return XRTM_INPUT_LTAU; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "input_yylex.l"
{ locus->statement = "ltau_l";          return XRTM_INPUT_LTAU_L; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "input_yylex.l"
{ locus->statement = "kernel_ampfac";   return XRTM_INPUT_KERNEL_AMPFAC; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "input_yylex.l"
{ locus->statement = "kernel_params";   return XRTM_INPUT_KERNEL_PARAMS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "input_yylex.l"
{ locus->statement = "kernel_ampfac_l"; return XRTM_INPUT_KERNEL_AMPFAC_L; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "input_yylex.l"
{ locus->statement = "kernel_params_l"; return XRTM_INPUT_KERNEL_PARAMS_L; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 "input_yylex.l"
{ locus->statement = "delta";           return XRTM_INPUT_DELTA; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 "input_yylex.l"
{ locus->statement = "F_iso_top_p";     return XRTM_INPUT_F_ISO_TOP_P; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 83 "input_yylex.l"
{ locus->statement = "F_iso_bot_p";     return XRTM_INPUT_F_ISO_BOT_P; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 84 "input_yylex.l"
{ locus->statement = "levels_b_p";      return XRTM_INPUT_LEVELS_B_P; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 85 "input_yylex.l"
{ locus->statement = "surface_b_p";     return XRTM_INPUT_SURFACE_B_P; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 "input_yylex.l"
{ locus->statement = "g_p";             return XRTM_INPUT_G_P; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 87 "input_yylex.l"
{ locus->statement = "coef_p";          return XRTM_INPUT_COEF_P; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 88 "input_yylex.l"
{ locus->statement = "coef_files_p";    return XRTM_INPUT_COEF_FILES_P; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 89 "input_yylex.l"
{ locus->statement = "omega_p";         return XRTM_INPUT_OMEGA_P; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 90 "input_yylex.l"
{ locus->statement = "ltau_p";          return XRTM_INPUT_LTAU_P; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 91 "input_yylex.l"
{ locus->statement = "kernel_ampfac_p"; return XRTM_INPUT_KERNEL_AMPFAC_P; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 92 "input_yylex.l"
{ locus->statement = "kernel_params_p"; return XRTM_INPUT_KERNEL_PARAMS_P; }
	YY_BREAK
/*
[A-Za-z_][-A-Za-z0-9_]*		{
     lex_type->s = strdup(yytext);
     return LEX_TYPE_IDENTIFIER;
}
 */
case 64:
#line 100 "input_yylex.l"
case 65:
YY_RULE_SETUP
#line 100 "input_yylex.l"
{
     char c;
     c = yytext[yyleng - 1];
     yytext[yyleng - 1] = '\0';
     lex_type->s = strdup(yytext + 1);
     yytext[yyleng - 1] = c;
     return LEX_TYPE_STRING;
}
	YY_BREAK
case 66:
#line 110 "input_yylex.l"
case 67:
#line 111 "input_yylex.l"
case 68:
YY_RULE_SETUP
#line 111 "input_yylex.l"
{
     lex_type->d = atof(yytext);
     return LEX_TYPE_DOUBLE;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 116 "input_yylex.l"
{
     lex_type->i = atoi(yytext);
     return LEX_TYPE_INT;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "input_yylex.l"
{
     lex_type->s = strdup(yytext);
     return LEX_TYPE_STRING;
}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 126 "input_yylex.l"
{ locus->line++; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 "input_yylex.l"
{ return yytext[0]; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "input_yylex.l"
ECHO;
	YY_BREAK
#line 1440 "input_yylex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 558 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 558 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 557);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 130 "input_yylex.l"



char *get_yytext() {

     return yytext;
}



void comment(locus_data *locus) {
	char c, prev = 0;
#ifdef __cplusplus
	while ((c = yyinput()) != 0)      /* (EOF maps to 0) */
#else
	while ((c =   input()) != 0)      /* (EOF maps to 0) */
#endif
	{
		if (c == '/' && prev == '*')
			return;
                else
                if (c == '\n')
                     locus->line++;
		prev = c;
	}
	input_error(locus, "unterminated comment");
}



void yypreinclude(FILE *fp) {

     yypush_buffer_state(yy_create_buffer(fp, YY_BUF_SIZE));
}



void yypostinclude() {

     yypop_buffer_state();
}



void yyrewind(int r, lex_type_data *type) {

    int i;

    for (i = yyleng - 1; i >= 0; --i)
        unput(yytext[i]);

    if (r == LEX_TYPE_STRING || r == LEX_TYPE_IDENTIFIER)
         free(type->s);
}

