!*******************************************************************************
! This file was generated by bindx version 0.01.  Edit at your own risk.
!*******************************************************************************

module xrtm_fd_int_f90

use iso_c_binding
use iso_fortran_env
use xrtm_int_f90


private

public :: xrtm_fd_type, &
          xrtm_fd_create_f90, &
          xrtm_fd_destroy_f90, &
          xrtm_fd_get_n_derivs_f90, &
          xrtm_fd_set_delta_f90, &
          xrtm_fd_get_delta_f90, &
          xrtm_fd_set_F_iso_top_p_1_f90, &
          xrtm_fd_set_F_iso_top_p_n_f90, &
          xrtm_fd_get_F_iso_top_p_f90, &
          xrtm_fd_set_F_iso_bot_p_1_f90, &
          xrtm_fd_set_F_iso_bot_p_n_f90, &
          xrtm_fd_get_F_iso_bot_p_f90, &
          xrtm_fd_set_levels_b_p_1_f90, &
          xrtm_fd_set_levels_b_p_n_f90, &
          xrtm_fd_get_levels_b_p_f90, &
          xrtm_fd_set_surface_b_p_1_f90, &
          xrtm_fd_set_surface_b_p_n_f90, &
          xrtm_fd_get_surface_b_p_f90, &
          xrtm_fd_set_g_p_11_f90, &
          xrtm_fd_set_g_p_n1_f90, &
          xrtm_fd_set_g_p_1n_f90, &
          xrtm_fd_set_g_p_nn_f90, &
          xrtm_fd_get_g_p_f90, &
          xrtm_fd_set_coef_p_11_f90, &
          xrtm_fd_set_coef_p_n1_f90, &
          xrtm_fd_set_coef_p_1n_f90, &
          xrtm_fd_set_coef_p_nn_f90, &
          xrtm_fd_get_coef_p_f90, &
          xrtm_fd_set_omega_p_11_f90, &
          xrtm_fd_set_omega_p_n1_f90, &
          xrtm_fd_set_omega_p_1n_f90, &
          xrtm_fd_set_omega_p_nn_f90, &
          xrtm_fd_get_omega_p_f90, &
          xrtm_fd_set_ltau_p_11_f90, &
          xrtm_fd_set_ltau_p_n1_f90, &
          xrtm_fd_set_ltau_p_1n_f90, &
          xrtm_fd_set_ltau_p_nn_f90, &
          xrtm_fd_get_ltau_p_f90, &
          xrtm_fd_set_kernel_ampfac_p_1_f90, &
          xrtm_fd_set_kernel_ampfac_p_n_f90, &
          xrtm_fd_get_kernel_ampfac_p_f90, &
          xrtm_fd_set_kernel_params_p_11_f90, &
          xrtm_fd_set_kernel_params_p_1n_f90, &
          xrtm_fd_set_kernel_params_p_n1_f90, &
          xrtm_fd_set_kernel_params_p_nn_f90, &
          xrtm_fd_get_kernel_params_p_f90, &
          xrtm_fd_solution_f90, &
          xrtm_fd_radiance_f90



!*******************************************************************************
!
!*******************************************************************************
integer, parameter, public :: XRTM_FD_METHOD_FORWARD = 0_int64
integer, parameter, public :: XRTM_FD_METHOD_BACKWARD = 1_int64
integer, parameter, public :: XRTM_FD_METHOD_CENTRAL = 2_int64



!*******************************************************************************
!
!*******************************************************************************
type, bind(c) :: xrtm_fd_type
     integer(c_signed_char) :: data(104)
end type xrtm_fd_type



!*******************************************************************************
!
!*******************************************************************************
interface
     integer(c_int) function xrtm_fd_create(d, xrtm, n_derivs) bind(c, name = "xrtm_fd_create")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     type(xrtm_type), intent(in) :: xrtm
     integer(c_int), intent(in), value :: n_derivs
     end function xrtm_fd_create
end interface


interface
     integer(c_int) function xrtm_fd_destroy(d) bind(c, name = "xrtm_fd_destroy")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     end function xrtm_fd_destroy
end interface


interface
     integer(c_int) function xrtm_fd_get_n_derivs(d) bind(c, name = "xrtm_fd_get_n_derivs")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     end function xrtm_fd_get_n_derivs
end interface


interface
     integer(c_int) function xrtm_fd_set_delta(d, delta) bind(c, name = "xrtm_fd_set_delta")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: delta(*)
     end function xrtm_fd_set_delta
end interface


interface
     integer(c_int) function xrtm_fd_get_delta(d, delta) bind(c, name = "xrtm_fd_get_delta")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(out) :: delta(*)
     end function xrtm_fd_get_delta
end interface


interface
     integer(c_int) function xrtm_fd_set_F_iso_top_p_1(d, i_deriv, F_iso_top_l) bind(c, name = "xrtm_fd_set_F_iso_top_p_1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: F_iso_top_l
     end function xrtm_fd_set_F_iso_top_p_1
end interface


interface
     integer(c_int) function xrtm_fd_set_F_iso_top_p_n(d, F_iso_top_l) bind(c, name = "xrtm_fd_set_F_iso_top_p_n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: F_iso_top_l(*)
     end function xrtm_fd_set_F_iso_top_p_n
end interface


interface
     real(c_double) function xrtm_fd_get_F_iso_top_p(d, i_deriv) bind(c, name = "xrtm_fd_get_F_iso_top_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_F_iso_top_p
end interface


interface
     integer(c_int) function xrtm_fd_set_F_iso_bot_p_1(d, i_deriv, F_iso_bot_l) bind(c, name = "xrtm_fd_set_F_iso_bot_p_1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: F_iso_bot_l
     end function xrtm_fd_set_F_iso_bot_p_1
end interface


interface
     integer(c_int) function xrtm_fd_set_F_iso_bot_p_n(d, F_iso_bot_l) bind(c, name = "xrtm_fd_set_F_iso_bot_p_n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: F_iso_bot_l(*)
     end function xrtm_fd_set_F_iso_bot_p_n
end interface


interface
     real(c_double) function xrtm_fd_get_F_iso_bot_p(d, i_deriv) bind(c, name = "xrtm_fd_get_F_iso_bot_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_F_iso_bot_p
end interface


interface
     integer(c_int) function xrtm_fd_set_levels_b_p_1(d, i_deriv, levels_b_l) bind(c, name = "xrtm_fd_set_levels_b_p_1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: levels_b_l(*)
     end function xrtm_fd_set_levels_b_p_1
end interface


interface
     integer(c_int) function xrtm_fd_set_levels_b_p_n_bindx_f90(d, levels_b_l) bind(c, name = "xrtm_fd_set_levels_b_p_n_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: levels_b_l(*)
     end function xrtm_fd_set_levels_b_p_n_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_levels_b_p(d, i_deriv, levels_b_l) bind(c, name = "xrtm_fd_get_levels_b_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(out) :: levels_b_l(*)
     end function xrtm_fd_get_levels_b_p
end interface


interface
     integer(c_int) function xrtm_fd_set_surface_b_p_1(d, i_deriv, surface_b_l) bind(c, name = "xrtm_fd_set_surface_b_p_1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: surface_b_l
     end function xrtm_fd_set_surface_b_p_1
end interface


interface
     integer(c_int) function xrtm_fd_set_surface_b_p_n(d, surface_b_l) bind(c, name = "xrtm_fd_set_surface_b_p_n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: surface_b_l(*)
     end function xrtm_fd_set_surface_b_p_n
end interface


interface
     real(c_double) function xrtm_fd_get_surface_b_p(d, i_deriv) bind(c, name = "xrtm_fd_get_surface_b_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_surface_b_p
end interface


interface
     integer(c_int) function xrtm_fd_set_g_p_11(d, i_layer, i_deriv, g_l) bind(c, name = "xrtm_fd_set_g_p_11")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: g_l
     end function xrtm_fd_set_g_p_11
end interface


interface
     integer(c_int) function xrtm_fd_set_g_p_n1(d, i_deriv, g_l) bind(c, name = "xrtm_fd_set_g_p_n1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: g_l(*)
     end function xrtm_fd_set_g_p_n1
end interface


interface
     integer(c_int) function xrtm_fd_set_g_p_1n(d, i_layer, g_l) bind(c, name = "xrtm_fd_set_g_p_1n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     real(c_double), intent(in) :: g_l(*)
     end function xrtm_fd_set_g_p_1n
end interface


interface
     integer(c_int) function xrtm_fd_set_g_p_nn_bindx_f90(d, g_l) bind(c, name = "xrtm_fd_set_g_p_nn_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: g_l(*)
     end function xrtm_fd_set_g_p_nn_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_g_p(d, i_layer, i_deriv) bind(c, name = "xrtm_fd_get_g_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_g_p
end interface


interface
     integer(c_int) function xrtm_fd_set_coef_p_11_bindx_f90(d, i_layer, i_deriv, coef_l) bind(c, name = "xrtm_fd_set_coef_p_11_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: coef_l(*)
     end function xrtm_fd_set_coef_p_11_bindx_f90
end interface


interface
     integer(c_int) function xrtm_fd_set_coef_p_n1_bindx_f90(d, i_deriv, coef_l) bind(c, name = "xrtm_fd_set_coef_p_n1_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: coef_l(*)
     end function xrtm_fd_set_coef_p_n1_bindx_f90
end interface


interface
     integer(c_int) function xrtm_fd_set_coef_p_1n_bindx_f90(d, i_layer, coef_l) bind(c, name = "xrtm_fd_set_coef_p_1n_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     real(c_double), intent(in) :: coef_l(*)
     end function xrtm_fd_set_coef_p_1n_bindx_f90
end interface


interface
     integer(c_int) function xrtm_fd_set_coef_p_nn_bindx_f90(d, coef_l) bind(c, name = "xrtm_fd_set_coef_p_nn_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: coef_l(*)
     end function xrtm_fd_set_coef_p_nn_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_coef_p(d, i_layer, i_deriv, i_elem, i_coef) bind(c, name = "xrtm_fd_get_coef_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     integer(c_int), intent(in), value :: i_elem
     integer(c_int), intent(in), value :: i_coef
     end function xrtm_fd_get_coef_p
end interface


interface
     integer(c_int) function xrtm_fd_set_omega_p_11(d, i_layer, i_deriv, omega_l) bind(c, name = "xrtm_fd_set_omega_p_11")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: omega_l
     end function xrtm_fd_set_omega_p_11
end interface


interface
     integer(c_int) function xrtm_fd_set_omega_p_n1(d, i_deriv, omega_l) bind(c, name = "xrtm_fd_set_omega_p_n1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: omega_l(*)
     end function xrtm_fd_set_omega_p_n1
end interface


interface
     integer(c_int) function xrtm_fd_set_omega_p_1n(d, i_layer, omega_l) bind(c, name = "xrtm_fd_set_omega_p_1n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     real(c_double), intent(in) :: omega_l(*)
     end function xrtm_fd_set_omega_p_1n
end interface


interface
     integer(c_int) function xrtm_fd_set_omega_p_nn_bindx_f90(d, omega_l) bind(c, name = "xrtm_fd_set_omega_p_nn_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: omega_l(*)
     end function xrtm_fd_set_omega_p_nn_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_omega_p(d, i_layer, i_deriv) bind(c, name = "xrtm_fd_get_omega_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_omega_p
end interface


interface
     integer(c_int) function xrtm_fd_set_ltau_p_11(d, i_layer, i_deriv, ltau_l) bind(c, name = "xrtm_fd_set_ltau_p_11")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: ltau_l
     end function xrtm_fd_set_ltau_p_11
end interface


interface
     integer(c_int) function xrtm_fd_set_ltau_p_n1(d, i_deriv, ltau_l) bind(c, name = "xrtm_fd_set_ltau_p_n1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: ltau_l(*)
     end function xrtm_fd_set_ltau_p_n1
end interface


interface
     integer(c_int) function xrtm_fd_set_ltau_p_1n(d, i_layer, ltau_l) bind(c, name = "xrtm_fd_set_ltau_p_1n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     real(c_double), intent(in) :: ltau_l(*)
     end function xrtm_fd_set_ltau_p_1n
end interface


interface
     integer(c_int) function xrtm_fd_set_ltau_p_nn_bindx_f90(d, ltau_l) bind(c, name = "xrtm_fd_set_ltau_p_nn_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(c_double), intent(in) :: ltau_l(*)
     end function xrtm_fd_set_ltau_p_nn_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_ltau_p(d, i_layer, i_deriv) bind(c, name = "xrtm_fd_get_ltau_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_layer
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_ltau_p
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_ampfac_p_1(d, i_kernel, i_deriv, ampfac_l) bind(c, name = "xrtm_fd_set_kernel_ampfac_p_1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in), value :: ampfac_l
     end function xrtm_fd_set_kernel_ampfac_p_1
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_ampfac_p_n(d, i_kernel, ampfac_l) bind(c, name = "xrtm_fd_set_kernel_ampfac_p_n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     real(c_double), intent(in) :: ampfac_l(*)
     end function xrtm_fd_set_kernel_ampfac_p_n
end interface


interface
     real(c_double) function xrtm_fd_get_kernel_ampfac_p(d, i_kernel, i_deriv) bind(c, name = "xrtm_fd_get_kernel_ampfac_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_deriv
     end function xrtm_fd_get_kernel_ampfac_p
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_params_p_11(d, i_kernel, i_deriv, i_param, param_l) bind(c, name = "xrtm_fd_set_kernel_params_p_11")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_deriv
     integer(c_int), intent(in), value :: i_param
     real(c_double), intent(in), value :: param_l
     end function xrtm_fd_set_kernel_params_p_11
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_params_p_1n(d, i_kernel, i_deriv, params_l) bind(c, name = "xrtm_fd_set_kernel_params_p_1n")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_deriv
     real(c_double), intent(in) :: params_l(*)
     end function xrtm_fd_set_kernel_params_p_1n
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_params_p_n1(d, i_kernel, i_param, params_l) bind(c, name = "xrtm_fd_set_kernel_params_p_n1")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_param
     real(c_double), intent(in) :: params_l(*)
     end function xrtm_fd_set_kernel_params_p_n1
end interface


interface
     integer(c_int) function xrtm_fd_set_kernel_params_p_nn_bindx_f90(d, i_kernel, params_l) bind(c, name = "xrtm_fd_set_kernel_params_p_nn_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     real(c_double), intent(in) :: params_l(*)
     end function xrtm_fd_set_kernel_params_p_nn_bindx_f90
end interface


interface
     real(c_double) function xrtm_fd_get_kernel_params_p(d, i_kernel, i_deriv, i_param) bind(c, name = "xrtm_fd_get_kernel_params_p")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: i_kernel
     integer(c_int), intent(in), value :: i_deriv
     integer(c_int), intent(in), value :: i_param
     end function xrtm_fd_get_kernel_params_p
end interface


interface
     integer(c_int) function xrtm_fd_solution_bindx_f90(d, solver, solutions, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m, mean_p, mean_m, mean_p_l, mean_m_l, flux_p, flux_m, flux_p_l, flux_m_l, flux_div, flux_div_l) bind(c, name = "xrtm_fd_solution_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: solver
     integer(c_int), intent(in), value :: solutions
     integer(c_int), intent(in), value :: method
     integer(c_int), intent(in), value :: n_out_phis
     real(c_double), intent(in) :: out_phis(*)
     real(c_double), intent(out) :: I_p(*)
     real(c_double), intent(out) :: I_m(*)
     real(c_double), intent(out) :: K_p(*)
     real(c_double), intent(out) :: K_m(*)
     real(c_double), intent(out) :: mean_p(*)
     real(c_double), intent(out) :: mean_m(*)
     real(c_double), intent(out) :: mean_p_l(*)
     real(c_double), intent(out) :: mean_m_l(*)
     real(c_double), intent(out) :: flux_p(*)
     real(c_double), intent(out) :: flux_m(*)
     real(c_double), intent(out) :: flux_p_l(*)
     real(c_double), intent(out) :: flux_m_l(*)
     real(c_double), intent(out) :: flux_div(*)
     real(c_double), intent(out) :: flux_div_l(*)
     end function xrtm_fd_solution_bindx_f90
end interface


interface
     integer(c_int) function xrtm_fd_radiance_bindx_f90(d, solver, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m) bind(c, name = "xrtm_fd_radiance_bindx_f90")
     use iso_c_binding
     import xrtm_fd_type
     import xrtm_type
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer(c_int), intent(in), value :: solver
     integer(c_int), intent(in), value :: method
     integer(c_int), intent(in), value :: n_out_phis
     real(c_double), intent(in) :: out_phis(*)
     real(c_double), intent(out) :: I_p(*)
     real(c_double), intent(out) :: I_m(*)
     real(c_double), intent(out) :: K_p(*)
     real(c_double), intent(out) :: K_m(*)
     end function xrtm_fd_radiance_bindx_f90
end interface



!*******************************************************************************
!
!*******************************************************************************
contains


subroutine xrtm_fd_create_f90(d, xrtm, n_derivs, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     type(xrtm_type), intent(in) :: xrtm
     integer, intent(in) :: n_derivs
     integer, intent(out) :: error
     error = xrtm_fd_create(d, xrtm, n_derivs)
end subroutine xrtm_fd_create_f90


subroutine xrtm_fd_destroy_f90(d, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(out) :: error
     error = xrtm_fd_destroy(d)
end subroutine xrtm_fd_destroy_f90


integer function xrtm_fd_get_n_derivs_f90(d)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     xrtm_fd_get_n_derivs_f90 = xrtm_fd_get_n_derivs(d)
end function xrtm_fd_get_n_derivs_f90


subroutine xrtm_fd_set_delta_f90(d, delta, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: delta(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_delta(d, delta)
end subroutine xrtm_fd_set_delta_f90


subroutine xrtm_fd_get_delta_f90(d, delta, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(out) :: delta(:)
     integer, intent(out) :: error
     error = xrtm_fd_get_delta(d, delta)
end subroutine xrtm_fd_get_delta_f90


subroutine xrtm_fd_set_F_iso_top_p_1_f90(d, i_deriv, F_iso_top_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: F_iso_top_l
     integer, intent(out) :: error
     error = xrtm_fd_set_F_iso_top_p_1(d, i_deriv, F_iso_top_l)
end subroutine xrtm_fd_set_F_iso_top_p_1_f90


subroutine xrtm_fd_set_F_iso_top_p_n_f90(d, F_iso_top_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: F_iso_top_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_F_iso_top_p_n(d, F_iso_top_l)
end subroutine xrtm_fd_set_F_iso_top_p_n_f90


real(8) function xrtm_fd_get_F_iso_top_p_f90(d, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     xrtm_fd_get_F_iso_top_p_f90 = xrtm_fd_get_F_iso_top_p(d, i_deriv)
end function xrtm_fd_get_F_iso_top_p_f90


subroutine xrtm_fd_set_F_iso_bot_p_1_f90(d, i_deriv, F_iso_bot_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: F_iso_bot_l
     integer, intent(out) :: error
     error = xrtm_fd_set_F_iso_bot_p_1(d, i_deriv, F_iso_bot_l)
end subroutine xrtm_fd_set_F_iso_bot_p_1_f90


subroutine xrtm_fd_set_F_iso_bot_p_n_f90(d, F_iso_bot_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: F_iso_bot_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_F_iso_bot_p_n(d, F_iso_bot_l)
end subroutine xrtm_fd_set_F_iso_bot_p_n_f90


real(8) function xrtm_fd_get_F_iso_bot_p_f90(d, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     xrtm_fd_get_F_iso_bot_p_f90 = xrtm_fd_get_F_iso_bot_p(d, i_deriv)
end function xrtm_fd_get_F_iso_bot_p_f90


subroutine xrtm_fd_set_levels_b_p_1_f90(d, i_deriv, levels_b_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: levels_b_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_levels_b_p_1(d, i_deriv, levels_b_l)
end subroutine xrtm_fd_set_levels_b_p_1_f90


subroutine xrtm_fd_set_levels_b_p_n_f90(d, levels_b_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: levels_b_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_levels_b_p_n_bindx_f90(d, levels_b_l)
end subroutine xrtm_fd_set_levels_b_p_n_f90


real(8) function xrtm_fd_get_levels_b_p_f90(d, i_deriv, levels_b_l)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(out) :: levels_b_l(:)
     xrtm_fd_get_levels_b_p_f90 = xrtm_fd_get_levels_b_p(d, i_deriv, levels_b_l)
end function xrtm_fd_get_levels_b_p_f90


subroutine xrtm_fd_set_surface_b_p_1_f90(d, i_deriv, surface_b_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: surface_b_l
     integer, intent(out) :: error
     error = xrtm_fd_set_surface_b_p_1(d, i_deriv, surface_b_l)
end subroutine xrtm_fd_set_surface_b_p_1_f90


subroutine xrtm_fd_set_surface_b_p_n_f90(d, surface_b_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: surface_b_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_surface_b_p_n(d, surface_b_l)
end subroutine xrtm_fd_set_surface_b_p_n_f90


real(8) function xrtm_fd_get_surface_b_p_f90(d, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     xrtm_fd_get_surface_b_p_f90 = xrtm_fd_get_surface_b_p(d, i_deriv)
end function xrtm_fd_get_surface_b_p_f90


subroutine xrtm_fd_set_g_p_11_f90(d, i_layer, i_deriv, g_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: g_l
     integer, intent(out) :: error
     error = xrtm_fd_set_g_p_11(d, i_layer, i_deriv, g_l)
end subroutine xrtm_fd_set_g_p_11_f90


subroutine xrtm_fd_set_g_p_n1_f90(d, i_deriv, g_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: g_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_g_p_n1(d, i_deriv, g_l)
end subroutine xrtm_fd_set_g_p_n1_f90


subroutine xrtm_fd_set_g_p_1n_f90(d, i_layer, g_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     real(8), intent(in) :: g_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_g_p_1n(d, i_layer, g_l)
end subroutine xrtm_fd_set_g_p_1n_f90


subroutine xrtm_fd_set_g_p_nn_f90(d, g_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: g_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_g_p_nn_bindx_f90(d, g_l)
end subroutine xrtm_fd_set_g_p_nn_f90


real(8) function xrtm_fd_get_g_p_f90(d, i_layer, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     xrtm_fd_get_g_p_f90 = xrtm_fd_get_g_p(d, i_layer, i_deriv)
end function xrtm_fd_get_g_p_f90


subroutine xrtm_fd_set_coef_p_11_f90(d, i_layer, i_deriv, coef_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: coef_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_coef_p_11_bindx_f90(d, i_layer, i_deriv, coef_l)
end subroutine xrtm_fd_set_coef_p_11_f90


subroutine xrtm_fd_set_coef_p_n1_f90(d, i_deriv, coef_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: coef_l(:,:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_coef_p_n1_bindx_f90(d, i_deriv, coef_l)
end subroutine xrtm_fd_set_coef_p_n1_f90


subroutine xrtm_fd_set_coef_p_1n_f90(d, i_layer, coef_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     real(8), intent(in) :: coef_l(:,:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_coef_p_1n_bindx_f90(d, i_layer, coef_l)
end subroutine xrtm_fd_set_coef_p_1n_f90


subroutine xrtm_fd_set_coef_p_nn_f90(d, coef_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: coef_l(:,:,:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_coef_p_nn_bindx_f90(d, coef_l)
end subroutine xrtm_fd_set_coef_p_nn_f90


real(8) function xrtm_fd_get_coef_p_f90(d, i_layer, i_deriv, i_elem, i_coef)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     integer, intent(in) :: i_elem
     integer, intent(in) :: i_coef
     xrtm_fd_get_coef_p_f90 = xrtm_fd_get_coef_p(d, i_layer, i_deriv, i_elem, i_coef)
end function xrtm_fd_get_coef_p_f90


subroutine xrtm_fd_set_omega_p_11_f90(d, i_layer, i_deriv, omega_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: omega_l
     integer, intent(out) :: error
     error = xrtm_fd_set_omega_p_11(d, i_layer, i_deriv, omega_l)
end subroutine xrtm_fd_set_omega_p_11_f90


subroutine xrtm_fd_set_omega_p_n1_f90(d, i_deriv, omega_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: omega_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_omega_p_n1(d, i_deriv, omega_l)
end subroutine xrtm_fd_set_omega_p_n1_f90


subroutine xrtm_fd_set_omega_p_1n_f90(d, i_layer, omega_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     real(8), intent(in) :: omega_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_omega_p_1n(d, i_layer, omega_l)
end subroutine xrtm_fd_set_omega_p_1n_f90


subroutine xrtm_fd_set_omega_p_nn_f90(d, omega_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: omega_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_omega_p_nn_bindx_f90(d, omega_l)
end subroutine xrtm_fd_set_omega_p_nn_f90


real(8) function xrtm_fd_get_omega_p_f90(d, i_layer, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     xrtm_fd_get_omega_p_f90 = xrtm_fd_get_omega_p(d, i_layer, i_deriv)
end function xrtm_fd_get_omega_p_f90


subroutine xrtm_fd_set_ltau_p_11_f90(d, i_layer, i_deriv, ltau_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: ltau_l
     integer, intent(out) :: error
     error = xrtm_fd_set_ltau_p_11(d, i_layer, i_deriv, ltau_l)
end subroutine xrtm_fd_set_ltau_p_11_f90


subroutine xrtm_fd_set_ltau_p_n1_f90(d, i_deriv, ltau_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: ltau_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_ltau_p_n1(d, i_deriv, ltau_l)
end subroutine xrtm_fd_set_ltau_p_n1_f90


subroutine xrtm_fd_set_ltau_p_1n_f90(d, i_layer, ltau_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     real(8), intent(in) :: ltau_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_ltau_p_1n(d, i_layer, ltau_l)
end subroutine xrtm_fd_set_ltau_p_1n_f90


subroutine xrtm_fd_set_ltau_p_nn_f90(d, ltau_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     real(8), intent(in) :: ltau_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_ltau_p_nn_bindx_f90(d, ltau_l)
end subroutine xrtm_fd_set_ltau_p_nn_f90


real(8) function xrtm_fd_get_ltau_p_f90(d, i_layer, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_layer
     integer, intent(in) :: i_deriv
     xrtm_fd_get_ltau_p_f90 = xrtm_fd_get_ltau_p(d, i_layer, i_deriv)
end function xrtm_fd_get_ltau_p_f90


subroutine xrtm_fd_set_kernel_ampfac_p_1_f90(d, i_kernel, i_deriv, ampfac_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: ampfac_l
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_ampfac_p_1(d, i_kernel, i_deriv, ampfac_l)
end subroutine xrtm_fd_set_kernel_ampfac_p_1_f90


subroutine xrtm_fd_set_kernel_ampfac_p_n_f90(d, i_kernel, ampfac_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     real(8), intent(in) :: ampfac_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_ampfac_p_n(d, i_kernel, ampfac_l)
end subroutine xrtm_fd_set_kernel_ampfac_p_n_f90


real(8) function xrtm_fd_get_kernel_ampfac_p_f90(d, i_kernel, i_deriv)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_deriv
     xrtm_fd_get_kernel_ampfac_p_f90 = xrtm_fd_get_kernel_ampfac_p(d, i_kernel, i_deriv)
end function xrtm_fd_get_kernel_ampfac_p_f90


subroutine xrtm_fd_set_kernel_params_p_11_f90(d, i_kernel, i_deriv, i_param, param_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_deriv
     integer, intent(in) :: i_param
     real(8), intent(in) :: param_l
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_params_p_11(d, i_kernel, i_deriv, i_param, param_l)
end subroutine xrtm_fd_set_kernel_params_p_11_f90


subroutine xrtm_fd_set_kernel_params_p_1n_f90(d, i_kernel, i_deriv, params_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_deriv
     real(8), intent(in) :: params_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_params_p_1n(d, i_kernel, i_deriv, params_l)
end subroutine xrtm_fd_set_kernel_params_p_1n_f90


subroutine xrtm_fd_set_kernel_params_p_n1_f90(d, i_kernel, i_param, params_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_param
     real(8), intent(in) :: params_l(:)
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_params_p_n1(d, i_kernel, i_param, params_l)
end subroutine xrtm_fd_set_kernel_params_p_n1_f90


subroutine xrtm_fd_set_kernel_params_p_nn_f90(d, i_kernel, params_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     real(8), intent(in) :: params_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_set_kernel_params_p_nn_bindx_f90(d, i_kernel, params_l)
end subroutine xrtm_fd_set_kernel_params_p_nn_f90


real(8) function xrtm_fd_get_kernel_params_p_f90(d, i_kernel, i_deriv, i_param)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: i_kernel
     integer, intent(in) :: i_deriv
     integer, intent(in) :: i_param
     xrtm_fd_get_kernel_params_p_f90 = xrtm_fd_get_kernel_params_p(d, i_kernel, i_deriv, i_param)
end function xrtm_fd_get_kernel_params_p_f90


subroutine xrtm_fd_solution_f90(d, solver, solutions, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m, mean_p, mean_m, mean_p_l, mean_m_l, flux_p, flux_m, flux_p_l, flux_m_l, flux_div, flux_div_l, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: solver
     integer, intent(in) :: solutions
     integer, intent(in) :: method
     integer, intent(in) :: n_out_phis
     real(8), intent(in) :: out_phis(:,:)
     real(8), intent(out) :: I_p(:,:,:,:)
     real(8), intent(out) :: I_m(:,:,:,:)
     real(8), intent(out) :: K_p(:,:,:,:,:)
     real(8), intent(out) :: K_m(:,:,:,:,:)
     real(8), intent(out) :: mean_p(:)
     real(8), intent(out) :: mean_m(:)
     real(8), intent(out) :: mean_p_l(:,:)
     real(8), intent(out) :: mean_m_l(:,:)
     real(8), intent(out) :: flux_p(:)
     real(8), intent(out) :: flux_m(:)
     real(8), intent(out) :: flux_p_l(:,:)
     real(8), intent(out) :: flux_m_l(:,:)
     real(8), intent(out) :: flux_div(:)
     real(8), intent(out) :: flux_div_l(:,:)
     integer, intent(out) :: error
     error = xrtm_fd_solution_bindx_f90(d, solver, solutions, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m, mean_p, mean_m, mean_p_l, mean_m_l, flux_p, flux_m, flux_p_l, flux_m_l, flux_div, flux_div_l)
end subroutine xrtm_fd_solution_f90


subroutine xrtm_fd_radiance_f90(d, solver, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m, error)
     implicit none
     type(xrtm_fd_type), intent(inout) :: d
     integer, intent(in) :: solver
     integer, intent(in) :: method
     integer, intent(in) :: n_out_phis
     real(8), intent(in) :: out_phis(:,:)
     real(8), intent(out) :: I_p(:,:,:,:)
     real(8), intent(out) :: I_m(:,:,:,:)
     real(8), intent(out) :: K_p(:,:,:,:,:)
     real(8), intent(out) :: K_m(:,:,:,:,:)
     integer, intent(out) :: error
     error = xrtm_fd_radiance_bindx_f90(d, solver, method, n_out_phis, out_phis, I_p, I_m, K_p, K_m)
end subroutine xrtm_fd_radiance_f90


end module xrtm_fd_int_f90
