/*******************************************************************************
 * This file was generated by bindx version 0.01.  Edit at your own risk.
 ******************************************************************************/

#include <gutil.h>

#include <xrtm_interface.h>

#ifdef __cplusplus
extern "C" {
#endif


int set_levels_z_levels_z_dims(xrtm_data *d, double *levels_z, size_t *dims)
{
    dims[0] = d->n_layers + 1;
    return 0;
}


int get_levels_z_levels_z_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_layers + 1;
    return 0;
}


int set_out_levels_out_levels_dims(xrtm_data *d, int *out_levels, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int get_out_levels_out_levels_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int set_out_taus_out_taus_dims(xrtm_data *d, double *out_taus, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int get_out_taus_out_taus_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int set_out_thetas_out_thetas_dims(xrtm_data *d, double *out_thetas, size_t *dims)
{
    dims[0] = d->n_out_thetas;
    return 0;
}


int get_out_thetas_out_thetas_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_out_thetas;
    return 0;
}


int set_F_iso_top_l_n_F_iso_top_l_dims(xrtm_data *d, double *F_iso_top_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_F_iso_bot_l_n_F_iso_bot_l_dims(xrtm_data *d, double *F_iso_bot_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_levels_b_levels_b_dims(xrtm_data *d, double *levels_b, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int get_levels_b_levels_b_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int set_levels_b_l_1_levels_b_l_dims(xrtm_data *d, int i_deriv, double *levels_b_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_levels_b_l_n_levels_b_l_dims(xrtm_data *d, double **levels_b_l, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int get_levels_b_l_levels_b_l_dims(xrtm_data *d, int i_deriv, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int set_surface_b_l_n_surface_b_l_dims(xrtm_data *d, double *surface_b_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_g_n_g_dims(xrtm_data *d, double *g, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_g_l_n1_g_l_dims(xrtm_data *d, int i_deriv, double *g_l, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_g_l_1n_g_l_dims(xrtm_data *d, int i_layer, double *g_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_g_l_nn_g_l_dims(xrtm_data *d, double **g_l, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_derivs;
    return 0;
}


int set_coef_1_coef_dims(xrtm_data *d, int i_layer, int n_coef_layer, double **coef, size_t *dims)
{
    dims[0] = d->n_elem;
    dims[1] = n_coef_layer;
    return 0;
}


int set_coef_n_n_coef_layer_dims(xrtm_data *d, int *n_coef_layer, double ***coef, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_coef_n_coef_dims(xrtm_data *d, int *n_coef_layer, double ***coef, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_elem;
    dims[2] = d->n_coef;
    return 0;
}


int set_coef_l_11_coef_l_dims(xrtm_data *d, int i_layer, int i_deriv, double **coef_l, size_t *dims)
{
    dims[0] = d->n_elem;
    dims[1] = d->n_coef_layer[i_layer];
    return 0;
}


int set_coef_l_n1_coef_l_dims(xrtm_data *d, int i_deriv, double ***coef_l, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_elem;
    dims[2] = d->n_coef;
    return 0;
}


int set_coef_l_1n_coef_l_dims(xrtm_data *d, int i_layer, double ***coef_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    dims[1] = d->n_elem;
    dims[2] = d->n_coef_layer[i_layer];
    return 0;
}


int set_coef_l_nn_coef_l_dims(xrtm_data *d, double ****coef_l, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_derivs;
    dims[2] = d->n_elem;
    dims[3] = d->n_coef;
    return 0;
}


int set_omega_n_omega_dims(xrtm_data *d, double *omega, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_omega_l_n1_omega_l_dims(xrtm_data *d, int i_deriv, double *omega_l, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_omega_l_1n_omega_l_dims(xrtm_data *d, int i_layer, double *omega_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_omega_l_nn_omega_l_dims(xrtm_data *d, double **omega_l, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_derivs;
    return 0;
}


int set_ltau_n_ltau_dims(xrtm_data *d, double *ltau, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_ltau_l_n1_ltau_l_dims(xrtm_data *d, int i_deriv, double *ltau_l, size_t *dims)
{
    dims[0] = d->n_layers;
    return 0;
}


int set_ltau_l_1n_ltau_l_dims(xrtm_data *d, int i_layer, double *ltau_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_ltau_l_nn_ltau_l_dims(xrtm_data *d, double **ltau_l, size_t *dims)
{
    dims[0] = d->n_layers;
    dims[1] = d->n_derivs;
    return 0;
}


int set_kernel_params_n_params_dims(xrtm_data *d, int i_kernel, double *params, size_t *dims)
{
    dims[0] = kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel]);
    return 0;
}


int set_kernel_ampfac_l_n_ampfac_l_dims(xrtm_data *d, int i_kernel, double *ampfac_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_kernel_params_l_1n_params_l_dims(xrtm_data *d, int i_kernel, int i_deriv, double *params_l, size_t *dims)
{
    dims[0] = kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel]);
    return 0;
}


int set_kernel_params_l_n1_params_l_dims(xrtm_data *d, int i_kernel, int i_param, double *params_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    return 0;
}


int set_kernel_params_l_nn_params_l_dims(xrtm_data *d, int i_kernel, double **params_l, size_t *dims)
{
    dims[0] = d->n_derivs;
    dims[1] = kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel]);
    return 0;
}


int qx_qx_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_quad;
    return 0;
}


int qw_qw_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_quad;
    return 0;
}


int kernel_qx_kernel_qx_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_kernel_quad;
    return 0;
}


int kernel_qw_kernel_qw_dims(xrtm_data *d, size_t *dims)
{
    dims[0] = d->n_kernel_quad;
    return 0;
}


int solution_out_phis_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_thetas;
    dims[1] = n_out_phis;
    return 0;
}


int solution_I_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_out_thetas_2;
    dims[2] = n_out_phis;
    dims[3] = d->n_stokes;
    return 0;
}


int solution_I_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_out_thetas_2;
    dims[2] = n_out_phis;
    dims[3] = d->n_stokes;
    return 0;
}


int solution_K_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    dims[2] = d->n_out_thetas_2;
    dims[3] = n_out_phis;
    dims[4] = d->n_stokes;
    return 0;
}


int solution_K_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    dims[2] = d->n_out_thetas_2;
    dims[3] = n_out_phis;
    dims[4] = d->n_stokes;
    return 0;
}


int solution_mean_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int solution_mean_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int solution_mean_p_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int solution_mean_m_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int solution_flux_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int solution_flux_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int solution_flux_p_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int solution_flux_m_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int solution_flux_div_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int solution_flux_div_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, int solutions, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int radiance_out_phis_dims(xrtm_data *d, enum xrtm_solver_mask solver, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_thetas;
    dims[1] = n_out_phis;
    return 0;
}


int radiance_I_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_out_thetas_2;
    dims[2] = n_out_phis;
    dims[3] = d->n_stokes;
    return 0;
}


int radiance_I_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_out_thetas_2;
    dims[2] = n_out_phis;
    dims[3] = d->n_stokes;
    return 0;
}


int radiance_K_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    dims[2] = d->n_out_thetas_2;
    dims[3] = n_out_phis;
    dims[4] = d->n_stokes;
    return 0;
}


int radiance_K_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, int n_out_phis, double **out_phis, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    dims[2] = d->n_out_thetas_2;
    dims[3] = n_out_phis;
    dims[4] = d->n_stokes;
    return 0;
}


int mean_radiance_mean_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int mean_radiance_mean_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int mean_radiance_mean_p_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int mean_radiance_mean_m_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int flux_flux_p_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int flux_flux_m_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int flux_flux_p_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int flux_flux_m_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


int flux_divergence_flux_div_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    return 0;
}


int flux_divergence_flux_div_l_dims(xrtm_data *d, enum xrtm_solver_mask solver, size_t *dims)
{
    dims[0] = d->n_out_levels;
    dims[1] = d->n_derivs;
    return 0;
}


#ifdef __cplusplus
}
#endif
