/*******************************************************************************
 * This file was generated by bindx version 0.01.  Edit at your own risk.
 ******************************************************************************/

#include <gutil.h>

#include <xrtm_fd_interface.h>

#ifdef __cplusplus
extern "C" {
#endif


int xrtm_fd_create_bindx_f77_(xrtm_fd_data *d, xrtm_data *xrtm, int *n_derivs_)
{
     int n_derivs;
     n_derivs = *n_derivs_;
     if (xrtm_fd_create(d, xrtm, n_derivs)) {
          fprintf(stderr, "ERROR: xrtm_fd_create()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_destroy_bindx_f77_(xrtm_fd_data *d)
{
     if (xrtm_fd_destroy(d)) {
          fprintf(stderr, "ERROR: xrtm_fd_destroy()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_get_n_derivs_bindx_f77_(xrtm_fd_data *d)
{
     if (xrtm_fd_get_n_derivs(d)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_n_derivs()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_delta_bindx_f77_(xrtm_fd_data *d, double *delta)
{
     if (xrtm_fd_set_delta(d, delta)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_delta()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_get_delta_bindx_f77_(xrtm_fd_data *d, double *delta)
{
     if (xrtm_fd_get_delta(d, delta)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_delta()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_f_iso_top_p_1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *F_iso_top_l_)
{
     int i_deriv;
     double F_iso_top_l;
     i_deriv = *i_deriv_;
     F_iso_top_l = *F_iso_top_l_;
     if (xrtm_fd_set_F_iso_top_p_1(d, i_deriv, F_iso_top_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_F_iso_top_p_1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_f_iso_top_p_n_bindx_f77_(xrtm_fd_data *d, double *F_iso_top_l)
{
     if (xrtm_fd_set_F_iso_top_p_n(d, F_iso_top_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_F_iso_top_p_n()\n");
          return -1;
     }
     return 0;
}


double xrtm_fd_get_f_iso_top_p_bindx_f77_(xrtm_fd_data *d, int *i_deriv_)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_F_iso_top_p(d, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_F_iso_top_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_f_iso_bot_p_1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *F_iso_bot_l_)
{
     int i_deriv;
     double F_iso_bot_l;
     i_deriv = *i_deriv_;
     F_iso_bot_l = *F_iso_bot_l_;
     if (xrtm_fd_set_F_iso_bot_p_1(d, i_deriv, F_iso_bot_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_F_iso_bot_p_1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_f_iso_bot_p_n_bindx_f77_(xrtm_fd_data *d, double *F_iso_bot_l)
{
     if (xrtm_fd_set_F_iso_bot_p_n(d, F_iso_bot_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_F_iso_bot_p_n()\n");
          return -1;
     }
     return 0;
}


double xrtm_fd_get_f_iso_bot_p_bindx_f77_(xrtm_fd_data *d, int *i_deriv_)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_F_iso_bot_p(d, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_F_iso_bot_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_levels_b_p_1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *levels_b_l)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_set_levels_b_p_1(d, i_deriv, levels_b_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_levels_b_p_1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_levels_b_p_n_bindx_f77_(xrtm_fd_data *d, double *levels_b_l)
{
     double **levels_b_l2;
     levels_b_l2 = array_from_mem2_d(levels_b_l, d->d->n_layers + 1, d->d->n_derivs);
     if (xrtm_fd_set_levels_b_p_n(d, levels_b_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_levels_b_p_n()\n");
          return -1;
     }
     free_array2_d(levels_b_l2);
     return 0;
}


double xrtm_fd_get_levels_b_p_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *levels_b_l)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_levels_b_p(d, i_deriv, levels_b_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_levels_b_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_surface_b_p_1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *surface_b_l_)
{
     int i_deriv;
     double surface_b_l;
     i_deriv = *i_deriv_;
     surface_b_l = *surface_b_l_;
     if (xrtm_fd_set_surface_b_p_1(d, i_deriv, surface_b_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_surface_b_p_1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_surface_b_p_n_bindx_f77_(xrtm_fd_data *d, double *surface_b_l)
{
     if (xrtm_fd_set_surface_b_p_n(d, surface_b_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_surface_b_p_n()\n");
          return -1;
     }
     return 0;
}


double xrtm_fd_get_surface_b_p_bindx_f77_(xrtm_fd_data *d, int *i_deriv_)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_surface_b_p(d, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_surface_b_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_g_p_11_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_, double *g_l_)
{
     int i_layer;
     int i_deriv;
     double g_l;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     g_l = *g_l_;
     if (xrtm_fd_set_g_p_11(d, i_layer, i_deriv, g_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_g_p_11()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_g_p_n1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *g_l)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_set_g_p_n1(d, i_deriv, g_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_g_p_n1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_g_p_1n_bindx_f77_(xrtm_fd_data *d, int *i_layer_, double *g_l)
{
     int i_layer;
     i_layer = *i_layer_;
     if (xrtm_fd_set_g_p_1n(d, i_layer, g_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_g_p_1n()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_g_p_nn_bindx_f77_(xrtm_fd_data *d, double *g_l)
{
     double **g_l2;
     g_l2 = array_from_mem2_d(g_l, d->d->n_layers, d->d->n_derivs);
     if (xrtm_fd_set_g_p_nn(d, g_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_g_p_nn()\n");
          return -1;
     }
     free_array2_d(g_l2);
     return 0;
}


double xrtm_fd_get_g_p_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_)
{
     int i_layer;
     int i_deriv;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_g_p(d, i_layer, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_g_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_coef_p_11_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_, double *coef_l)
{
     int i_layer;
     int i_deriv;
     double **coef_l2;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     coef_l2 = array_from_mem2_d(coef_l, d->d->n_elem, d->d->n_coef_layer[i_layer]);
     if (xrtm_fd_set_coef_p_11(d, i_layer, i_deriv, coef_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_coef_p_11()\n");
          return -1;
     }
     free_array2_d(coef_l2);
     return 0;
}


int xrtm_fd_set_coef_p_n1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *coef_l)
{
     int i_deriv;
     double ***coef_l2;
     i_deriv = *i_deriv_;
     coef_l2 = array_from_mem3_d(coef_l, d->d->n_layers, d->d->n_elem, d->d->n_coef);
     if (xrtm_fd_set_coef_p_n1(d, i_deriv, coef_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_coef_p_n1()\n");
          return -1;
     }
     free_array3_d(coef_l2);
     return 0;
}


int xrtm_fd_set_coef_p_1n_bindx_f77_(xrtm_fd_data *d, int *i_layer_, double *coef_l)
{
     int i_layer;
     double ***coef_l2;
     i_layer = *i_layer_;
     coef_l2 = array_from_mem3_d(coef_l, d->d->n_derivs, d->d->n_elem, d->d->n_coef_layer[i_layer]);
     if (xrtm_fd_set_coef_p_1n(d, i_layer, coef_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_coef_p_1n()\n");
          return -1;
     }
     free_array3_d(coef_l2);
     return 0;
}


int xrtm_fd_set_coef_p_nn_bindx_f77_(xrtm_fd_data *d, double *coef_l)
{
     double ****coef_l2;
     coef_l2 = array_from_mem4_d(coef_l, d->d->n_layers, d->d->n_derivs, d->d->n_elem, d->d->n_coef);
     if (xrtm_fd_set_coef_p_nn(d, coef_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_coef_p_nn()\n");
          return -1;
     }
     free_array4_d(coef_l2);
     return 0;
}


double xrtm_fd_get_coef_p_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_, int *i_elem_, int *i_coef_)
{
     int i_layer;
     int i_deriv;
     int i_elem;
     int i_coef;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     i_elem = *i_elem_;
     i_coef = *i_coef_;
     if (xrtm_fd_get_coef_p(d, i_layer, i_deriv, i_elem, i_coef)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_coef_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_omega_p_11_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_, double *omega_l_)
{
     int i_layer;
     int i_deriv;
     double omega_l;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     omega_l = *omega_l_;
     if (xrtm_fd_set_omega_p_11(d, i_layer, i_deriv, omega_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_omega_p_11()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_omega_p_n1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *omega_l)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_set_omega_p_n1(d, i_deriv, omega_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_omega_p_n1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_omega_p_1n_bindx_f77_(xrtm_fd_data *d, int *i_layer_, double *omega_l)
{
     int i_layer;
     i_layer = *i_layer_;
     if (xrtm_fd_set_omega_p_1n(d, i_layer, omega_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_omega_p_1n()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_omega_p_nn_bindx_f77_(xrtm_fd_data *d, double *omega_l)
{
     double **omega_l2;
     omega_l2 = array_from_mem2_d(omega_l, d->d->n_layers, d->d->n_derivs);
     if (xrtm_fd_set_omega_p_nn(d, omega_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_omega_p_nn()\n");
          return -1;
     }
     free_array2_d(omega_l2);
     return 0;
}


double xrtm_fd_get_omega_p_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_)
{
     int i_layer;
     int i_deriv;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_omega_p(d, i_layer, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_omega_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_ltau_p_11_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_, double *ltau_l_)
{
     int i_layer;
     int i_deriv;
     double ltau_l;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     ltau_l = *ltau_l_;
     if (xrtm_fd_set_ltau_p_11(d, i_layer, i_deriv, ltau_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_ltau_p_11()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_ltau_p_n1_bindx_f77_(xrtm_fd_data *d, int *i_deriv_, double *ltau_l)
{
     int i_deriv;
     i_deriv = *i_deriv_;
     if (xrtm_fd_set_ltau_p_n1(d, i_deriv, ltau_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_ltau_p_n1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_ltau_p_1n_bindx_f77_(xrtm_fd_data *d, int *i_layer_, double *ltau_l)
{
     int i_layer;
     i_layer = *i_layer_;
     if (xrtm_fd_set_ltau_p_1n(d, i_layer, ltau_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_ltau_p_1n()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_ltau_p_nn_bindx_f77_(xrtm_fd_data *d, double *ltau_l)
{
     double **ltau_l2;
     ltau_l2 = array_from_mem2_d(ltau_l, d->d->n_layers, d->d->n_derivs);
     if (xrtm_fd_set_ltau_p_nn(d, ltau_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_ltau_p_nn()\n");
          return -1;
     }
     free_array2_d(ltau_l2);
     return 0;
}


double xrtm_fd_get_ltau_p_bindx_f77_(xrtm_fd_data *d, int *i_layer_, int *i_deriv_)
{
     int i_layer;
     int i_deriv;
     i_layer = *i_layer_;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_ltau_p(d, i_layer, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_ltau_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_ampfac_p_1_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_deriv_, double *ampfac_l_)
{
     int i_kernel;
     int i_deriv;
     double ampfac_l;
     i_kernel = *i_kernel_;
     i_deriv = *i_deriv_;
     ampfac_l = *ampfac_l_;
     if (xrtm_fd_set_kernel_ampfac_p_1(d, i_kernel, i_deriv, ampfac_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_ampfac_p_1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_ampfac_p_n_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, double *ampfac_l)
{
     int i_kernel;
     i_kernel = *i_kernel_;
     if (xrtm_fd_set_kernel_ampfac_p_n(d, i_kernel, ampfac_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_ampfac_p_n()\n");
          return -1;
     }
     return 0;
}


double xrtm_fd_get_kernel_ampfac_p_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_deriv_)
{
     int i_kernel;
     int i_deriv;
     i_kernel = *i_kernel_;
     i_deriv = *i_deriv_;
     if (xrtm_fd_get_kernel_ampfac_p(d, i_kernel, i_deriv)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_kernel_ampfac_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_params_p_11_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_deriv_, int *i_param_, double *param_l_)
{
     int i_kernel;
     int i_deriv;
     int i_param;
     double param_l;
     i_kernel = *i_kernel_;
     i_deriv = *i_deriv_;
     i_param = *i_param_;
     param_l = *param_l_;
     if (xrtm_fd_set_kernel_params_p_11(d, i_kernel, i_deriv, i_param, param_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_params_p_11()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_params_p_1n_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_deriv_, double *params_l)
{
     int i_kernel;
     int i_deriv;
     i_kernel = *i_kernel_;
     i_deriv = *i_deriv_;
     if (xrtm_fd_set_kernel_params_p_1n(d, i_kernel, i_deriv, params_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_params_p_1n()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_params_p_n1_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_param_, double *params_l)
{
     int i_kernel;
     int i_param;
     i_kernel = *i_kernel_;
     i_param = *i_param_;
     if (xrtm_fd_set_kernel_params_p_n1(d, i_kernel, i_param, params_l)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_params_p_n1()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_set_kernel_params_p_nn_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, double *params_l)
{
     int i_kernel;
     double **params_l2;
     i_kernel = *i_kernel_;
     params_l2 = array_from_mem2_d(params_l, d->d->n_derivs, kernel_n_params((enum xrtm_kernel_type) d->d->kernels[i_kernel]));
     if (xrtm_fd_set_kernel_params_p_nn(d, i_kernel, params_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_set_kernel_params_p_nn()\n");
          return -1;
     }
     free_array2_d(params_l2);
     return 0;
}


double xrtm_fd_get_kernel_params_p_bindx_f77_(xrtm_fd_data *d, int *i_kernel_, int *i_deriv_, int *i_param_)
{
     int i_kernel;
     int i_deriv;
     int i_param;
     i_kernel = *i_kernel_;
     i_deriv = *i_deriv_;
     i_param = *i_param_;
     if (xrtm_fd_get_kernel_params_p(d, i_kernel, i_deriv, i_param)) {
          fprintf(stderr, "ERROR: xrtm_fd_get_kernel_params_p()\n");
          return -1;
     }
     return 0;
}


int xrtm_fd_solution_bindx_f77_(xrtm_fd_data *d, enum xrtm_solver_mask *solver_, int *solutions_, enum xrtm_fd_method_type *method_, int *n_out_phis_, double *out_phis, double *I_p, double *I_m, double *K_p, double *K_m, double *mean_p, double *mean_m, double *mean_p_l, double *mean_m_l, double *flux_p, double *flux_m, double *flux_p_l, double *flux_m_l, double *flux_div, double *flux_div_l)
{
     enum xrtm_solver_mask solver;
     int solutions;
     enum xrtm_fd_method_type method;
     int n_out_phis;
     double **out_phis2;
     double ****I_p2;
     double ****I_m2;
     double *****K_p2;
     double *****K_m2;
     double **mean_p_l2;
     double **mean_m_l2;
     double **flux_p_l2;
     double **flux_m_l2;
     double **flux_div_l2;
     solver = *solver_;
     solutions = *solutions_;
     method = *method_;
     n_out_phis = *n_out_phis_;
     out_phis2 = array_from_mem2_d(out_phis, d->d->n_umus, n_out_phis);
     I_p2 = array_from_mem4_d(I_p, d->d->n_ulevels, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     I_m2 = array_from_mem4_d(I_m, d->d->n_ulevels, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     K_p2 = array_from_mem5_d(K_p, d->d->n_ulevels, d->d->n_derivs, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     K_m2 = array_from_mem5_d(K_m, d->d->n_ulevels, d->d->n_derivs, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     mean_p_l2 = array_from_mem2_d(mean_p_l, d->d->n_ulevels, d->d->n_derivs);
     mean_m_l2 = array_from_mem2_d(mean_m_l, d->d->n_ulevels, d->d->n_derivs);
     flux_p_l2 = array_from_mem2_d(flux_p_l, d->d->n_ulevels, d->d->n_derivs);
     flux_m_l2 = array_from_mem2_d(flux_m_l, d->d->n_ulevels, d->d->n_derivs);
     flux_div_l2 = array_from_mem2_d(flux_div_l, d->d->n_ulevels, d->d->n_derivs);
     if (xrtm_fd_solution(d, (enum xrtm_solver_mask) solver, solutions, (enum xrtm_fd_method_type) method, n_out_phis, out_phis2, I_p2, I_m2, K_p2, K_m2, mean_p, mean_m, mean_p_l2, mean_m_l2, flux_p, flux_m, flux_p_l2, flux_m_l2, flux_div, flux_div_l2)) {
          fprintf(stderr, "ERROR: xrtm_fd_solution()\n");
          return -1;
     }
     free_array2_d(out_phis2);
     free_array4_d(I_p2);
     free_array4_d(I_m2);
     free_array5_d(K_p2);
     free_array5_d(K_m2);
     free_array2_d(mean_p_l2);
     free_array2_d(mean_m_l2);
     free_array2_d(flux_p_l2);
     free_array2_d(flux_m_l2);
     free_array2_d(flux_div_l2);
     return 0;
}


int xrtm_fd_radiance_bindx_f77_(xrtm_fd_data *d, enum xrtm_solver_mask *solver_, enum xrtm_fd_method_type *method_, int *n_out_phis_, double *out_phis, double *I_p, double *I_m, double *K_p, double *K_m)
{
     enum xrtm_solver_mask solver;
     enum xrtm_fd_method_type method;
     int n_out_phis;
     double **out_phis2;
     double ****I_p2;
     double ****I_m2;
     double *****K_p2;
     double *****K_m2;
     solver = *solver_;
     method = *method_;
     n_out_phis = *n_out_phis_;
     out_phis2 = array_from_mem2_d(out_phis, d->d->n_umus, n_out_phis);
     I_p2 = array_from_mem4_d(I_p, d->d->n_ulevels, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     I_m2 = array_from_mem4_d(I_m, d->d->n_ulevels, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     K_p2 = array_from_mem5_d(K_p, d->d->n_ulevels, d->d->n_derivs, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     K_m2 = array_from_mem5_d(K_m, d->d->n_ulevels, d->d->n_derivs, d->d->n_umus == 0 ? d->d->n_quad : d->d->n_umus, n_out_phis, d->d->n_stokes);
     if (xrtm_fd_radiance(d, (enum xrtm_solver_mask) solver, (enum xrtm_fd_method_type) method, n_out_phis, out_phis2, I_p2, I_m2, K_p2, K_m2)) {
          fprintf(stderr, "ERROR: xrtm_fd_radiance()\n");
          return -1;
     }
     free_array2_d(out_phis2);
     free_array4_d(I_p2);
     free_array4_d(I_m2);
     free_array5_d(K_p2);
     free_array5_d(K_m2);
     return 0;
}


#ifdef __cplusplus
}
#endif
