/*******************************************************************************
 * This file was generated by bindx version 0.01.  Edit at your own risk.
 ******************************************************************************/

#include <Python.h>
#include <structmember.h>
#ifndef Py_USING_UNICODE
#define Py_USING_UNICODE
#endif
#include <numpy/arrayobject.h>

#include <gutil.h>

#include <xrtm_interface.h>


typedef struct {
     PyObject_HEAD
     xrtm_data xrtm;
} xrtm_data_py;


static PyObject *XRTMError;


static PyObject *xrtm_new(PyTypeObject *type, PyObject *args, PyObject *kwds)
{
     xrtm_data_py *self;
     self = (xrtm_data_py *) type->tp_alloc(type, 0);
     if (self != NULL) { }
     return (PyObject *) self;
}


static int list_to_mask(PyObject *list, int *mask, int (*name_to_mask)(const char *name), const char *name)
{
     int i;
     int n;
     int r;
     char *format;
     char *error;
     *mask = 0;
     n = PyList_Size(list);
     for (i = 0; i < n; ++i) {
#if PY_MAJOR_VERSION < 3
          r = name_to_mask(PyString_AsString(PyList_GetItem(list, i)));
#else
          r = name_to_mask(PyUnicode_AsUTF8 (PyList_GetItem(list, i)));
#endif
          if (r == -1) {
               format = "ERROR: %s()";
               error  = malloc(strlen(format) - 2 + strlen(name) + 1);
               sprintf(error, format, name);
               PyErr_SetString(XRTMError, error);
               free(error);
               return -1;
          }
          *mask |= r;
     }
     return 0;
}


static int list_to_array(PyObject *list, int *n, int **array, int (*name_to_value)(const char *name), const char *name)
{
     int i;
     int r;
     char *format;
     char *error;
     *n = PyList_Size(list);
     *array = malloc(*n * sizeof(int));
     for (i = 0; i < *n; ++i) {
#if PY_MAJOR_VERSION < 3
          r = name_to_value(PyString_AsString(PyList_GetItem(list, i)));
#else
          r = name_to_value(PyUnicode_AsUTF8 (PyList_GetItem(list, i)));
#endif
          if (r == -1) {
               format = "ERROR: %s()";
               error  = malloc(strlen(format) - 2 + strlen(name) + 1);
               sprintf(error, format, name);
               PyErr_SetString(XRTMError, error);
               free(error);
               return -1;
          }
          (*array)[i] = r;
     }
     return 0;
}


static int check_pyarray_shape(PyObject *array, const char *name, int n, ...)
{
     int i;
     int dim;
     int n_py;
     int dim_py;
     va_list valist;
     n_py = PyArray_NDIM((PyArrayObject *) array);
     if (n_py != n) {
          PyErr_Format(XRTMError, "ERROR: Number of dimensions for %s input (%d) must be == %d", name, n_py);
          return -1;
     }
     va_start(valist, n);
     for (i = 0; i < n; ++i) {
          dim = va_arg(valist, int);
          dim_py = PyArray_DIM((PyArrayObject *) array, i);
          if (dim_py != dim) {
              PyErr_Format(XRTMError, "ERROR: Dimension %d of %s input (%d) must be == %d", i, name, dim_py, dim);
              return -1;
          }
     }
     va_end(valist);
     return 0;
}


static void *array_from_ndarray(PyObject *ndarray, size_t size)
{
     int i;
     int n_dims;
     size_t *dims;
     void *array;
     n_dims = PyArray_NDIM((PyArrayObject *) ndarray);
     dims = malloc(n_dims * sizeof(long));
     for (i = 0; i < n_dims; ++i)
          dims[i] = PyArray_DIM((PyArrayObject *) ndarray, i);
     array = array_from_mem(PyArray_DATA((PyArrayObject *) ndarray), n_dims, dims, size, 1);
     free(dims);
     return array;
}


static int xrtm_init(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int options;
     PyObject *options_list;
     int solvers;
     PyObject *solvers_list;
     int max_coef;
     int n_quad;
     int n_stokes;
     int n_derivs;
     int n_layers;
     int n_theta_0s;
     int n_kernels;
     int n_kernel_quad;
     enum xrtm_kernel_type *kernels;
     PyObject *kernels_list;
     int n_out_levels;
     int n_out_thetas;
     if (! PyArg_ParseTuple(args, "OOiiiiiiiOii", &options_list, &solvers_list, &max_coef, &n_quad, &n_stokes, &n_derivs, &n_layers, &n_theta_0s, &n_kernel_quad, &kernels_list, &n_out_levels, &n_out_thetas))
          return -1;
     if (list_to_mask(options_list, &options, (int (*)(const char *)) xrtm_option_name_to_mask, "xrtm_option_name_to_mask"))
          return -1;
     if (list_to_mask(solvers_list, &solvers, (int (*)(const char *)) xrtm_solver_name_to_mask, "xrtm_solver_name_to_mask"))
          return -1;
     if (list_to_array(kernels_list, &n_kernels, (int **) &kernels, (int (*)(const char *)) xrtm_kernel_name_to_value, "xrtm_kernel_name_to_value"))
          return -1;
     r = xrtm_create(d, options, solvers, max_coef, n_quad, n_stokes, n_derivs, n_layers, n_theta_0s, n_kernels, n_kernel_quad, (enum xrtm_kernel_type *) kernels, n_out_levels, n_out_thetas);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_create()");
          return -1;
     }
     free(kernels);
     return 0;
}


static void xrtm_dealloc(xrtm_data_py *self)
{
     int r;
     xrtm_data *d = &self->xrtm;
     r = xrtm_destroy(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_destroy()");
          return ;
     }
#if PY_MAJOR_VERSION < 3
     self->ob_type->tp_free((PyObject *) self);
#else
     ((PyObject*)(self))->ob_type->tp_free((PyObject *) self);
#endif
}


static PyObject *xrtm_get_options_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_options(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_options()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_solvers_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_solvers(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_solvers()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_max_coef_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_max_coef(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_max_coef()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_quad_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_quad(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_quad()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_stokes_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_stokes(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_stokes()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_derivs_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_derivs(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_derivs()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_layers_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_layers(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_layers()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_kernels_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_kernels(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_kernels()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_kernel_quad_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_kernel_quad(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_kernel_quad()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_kernel_py(xrtm_data_py *self, PyObject *args)
{
     enum xrtm_kernel_type r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     if (! PyArg_ParseTuple(args, "i", &i_kernel))
          return NULL;
     r = xrtm_get_kernel(d, i_kernel);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_kernel()");
          return NULL;
     }
     return Py_BuildValue("s", r);
}


static PyObject *xrtm_get_n_out_levels_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_out_levels(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_out_levels()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_out_thetas_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_out_thetas(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_out_thetas()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_n_out_thetas_2_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_n_out_thetas_2(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_out_thetas_2()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_set_doub_d_tau_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double d_tau;
     if (! PyArg_ParseTuple(args, "d", &d_tau))
          return NULL;
     r = xrtm_set_doub_d_tau(d, d_tau);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_doub_d_tau()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_doub_d_tau_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_doub_d_tau(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_doub_d_tau()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_pade_params_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int pade_s;
     int pade_r;
     if (! PyArg_ParseTuple(args, "ii", &pade_s, &pade_r))
          return NULL;
     r = xrtm_set_pade_params(d, pade_s, pade_r);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_pade_params()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_pade_params_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int pade_s;
     int pade_r;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_pade_params(d, &pade_s, &pade_r);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_pade_params()");
          return NULL;
     }
     return Py_BuildValue("ii", pade_s, pade_r);
}


static PyObject *xrtm_set_sos_params_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int max_os;
     double max_tau;
     double sos_tol;
     if (! PyArg_ParseTuple(args, "idd", &max_os, &max_tau, &sos_tol))
          return NULL;
     r = xrtm_set_sos_params(d, max_os, max_tau, sos_tol);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_sos_params()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_sos_params_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int max_os;
     double max_tau;
     double sos_tol;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_sos_params(d, &max_os, &max_tau, &sos_tol);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_sos_params()");
          return NULL;
     }
     return Py_BuildValue("idd", max_os, max_tau, sos_tol);
}


static PyObject *xrtm_set_fourier_tol_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double fourier_tol;
     if (! PyArg_ParseTuple(args, "d", &fourier_tol))
          return NULL;
     r = xrtm_set_fourier_tol(d, fourier_tol);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_fourier_tol()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_fourier_tol_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_fourier_tol(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_fourier_tol()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_lambda_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double lambda;
     if (! PyArg_ParseTuple(args, "d", &lambda))
          return NULL;
     r = xrtm_set_lambda(d, lambda);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_lambda()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_lambda_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_lambda(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_lambda()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_planet_r_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double planet_r;
     if (! PyArg_ParseTuple(args, "d", &planet_r))
          return NULL;
     r = xrtm_set_planet_r(d, planet_r);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_planet_r()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_planet_r_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_planet_r(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_planet_r()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_levels_z_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *levels_z_object  = NULL;
     PyObject *levels_z_ndarray = NULL;
     double *levels_z;
     if (! PyArg_ParseTuple(args, "O", &levels_z_object))
          return NULL;
     levels_z_ndarray = PyArray_FROM_OTF(levels_z_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (levels_z_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(levels_z_ndarray, "levels_z", 1, d->n_out_levels) < 0)
          return NULL;
     levels_z = (double *) array_from_ndarray(levels_z_ndarray, 8);
     r = xrtm_set_levels_z(d, levels_z);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_levels_z()");
          return NULL;
     }
     Py_DECREF(levels_z_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_levels_z_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *levels_z_ndarray = NULL;
     double *levels_z;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_out_levels;
     levels_z_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (levels_z_ndarray == NULL)
          return NULL;
     levels_z = (double *) array_from_ndarray(levels_z_ndarray, 8);
     r = xrtm_get_levels_z(d, levels_z);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_levels_z()");
          return NULL;
     }
     return Py_BuildValue("O", levels_z_ndarray);
}


static PyObject *xrtm_set_out_levels_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *out_levels_object  = NULL;
     PyObject *out_levels_ndarray = NULL;
     int *out_levels;
     if (! PyArg_ParseTuple(args, "O", &out_levels_object))
          return NULL;
     out_levels_ndarray = PyArray_FROM_OTF(out_levels_object, NPY_INT, NPY_ARRAY_IN_ARRAY);
     if (out_levels_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(out_levels_ndarray, "out_levels", 1, d->n_out_levels) < 0)
          return NULL;
     out_levels = (int *) array_from_ndarray(out_levels_ndarray, 4);
     r = xrtm_set_out_levels(d, out_levels);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_out_levels()");
          return NULL;
     }
     Py_DECREF(out_levels_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_out_levels_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *out_levels_ndarray = NULL;
     int *out_levels;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_out_levels;
     out_levels_ndarray = PyArray_SimpleNew(1, dims, NPY_INT);
     if (out_levels_ndarray == NULL)
          return NULL;
     out_levels = (int *) array_from_ndarray(out_levels_ndarray, 4);
     r = xrtm_get_out_levels(d, out_levels);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_out_levels()");
          return NULL;
     }
     return Py_BuildValue("O", out_levels_ndarray);
}


static PyObject *xrtm_set_out_taus_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *out_taus_object  = NULL;
     PyObject *out_taus_ndarray = NULL;
     double *out_taus;
     if (! PyArg_ParseTuple(args, "O", &out_taus_object))
          return NULL;
     out_taus_ndarray = PyArray_FROM_OTF(out_taus_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (out_taus_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(out_taus_ndarray, "out_taus", 1, d->n_out_levels) < 0)
          return NULL;
     out_taus = (double *) array_from_ndarray(out_taus_ndarray, 8);
     r = xrtm_set_out_taus(d, out_taus);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_out_taus()");
          return NULL;
     }
     Py_DECREF(out_taus_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_out_taus_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *out_taus_ndarray = NULL;
     double *out_taus;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_out_levels;
     out_taus_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (out_taus_ndarray == NULL)
          return NULL;
     out_taus = (double *) array_from_ndarray(out_taus_ndarray, 8);
     r = xrtm_get_out_taus(d, out_taus);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_out_taus()");
          return NULL;
     }
     return Py_BuildValue("O", out_taus_ndarray);
}


static PyObject *xrtm_set_out_thetas_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *out_thetas_object  = NULL;
     PyObject *out_thetas_ndarray = NULL;
     double *out_thetas;
     if (! PyArg_ParseTuple(args, "O", &out_thetas_object))
          return NULL;
     out_thetas_ndarray = PyArray_FROM_OTF(out_thetas_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (out_thetas_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(out_thetas_ndarray, "out_thetas", 1, d->n_out_thetas) < 0)
          return NULL;
     out_thetas = (double *) array_from_ndarray(out_thetas_ndarray, 8);
     r = xrtm_set_out_thetas(d, out_thetas);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_out_thetas()");
          return NULL;
     }
     Py_DECREF(out_thetas_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_out_thetas_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *out_thetas_ndarray = NULL;
     double *out_thetas;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_out_thetas;
     out_thetas_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (out_thetas_ndarray == NULL)
          return NULL;
     out_thetas = (double *) array_from_ndarray(out_thetas_ndarray, 8);
     r = xrtm_get_out_thetas(d, out_thetas);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_out_thetas()");
          return NULL;
     }
     return Py_BuildValue("O", out_thetas_ndarray);
}


static PyObject *xrtm_set_F_iso_top_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double F_iso_top;
     if (! PyArg_ParseTuple(args, "d", &F_iso_top))
          return NULL;
     r = xrtm_set_F_iso_top(d, F_iso_top);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_top()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_F_iso_top_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_F_iso_top(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_F_iso_top()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_F_iso_top_l_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     double F_iso_top_l;
     if (! PyArg_ParseTuple(args, "id", &i_deriv, &F_iso_top_l))
          return NULL;
     r = xrtm_set_F_iso_top_l_1(d, i_deriv, F_iso_top_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_top_l_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_F_iso_top_l_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *F_iso_top_l_object  = NULL;
     PyObject *F_iso_top_l_ndarray = NULL;
     double *F_iso_top_l;
     if (! PyArg_ParseTuple(args, "O", &F_iso_top_l_object))
          return NULL;
     F_iso_top_l_ndarray = PyArray_FROM_OTF(F_iso_top_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (F_iso_top_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(F_iso_top_l_ndarray, "F_iso_top_l", 1, d->n_derivs) < 0)
          return NULL;
     F_iso_top_l = (double *) array_from_ndarray(F_iso_top_l_ndarray, 8);
     r = xrtm_set_F_iso_top_l_n(d, F_iso_top_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_top_l_n()");
          return NULL;
     }
     Py_DECREF(F_iso_top_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_F_iso_top_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "i", &i_deriv))
          return NULL;
     r = xrtm_get_F_iso_top_l(d, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_F_iso_top_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_F_iso_bot_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double F_iso_bot;
     if (! PyArg_ParseTuple(args, "d", &F_iso_bot))
          return NULL;
     r = xrtm_set_F_iso_bot(d, F_iso_bot);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_bot()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_F_iso_bot_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_F_iso_bot(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_F_iso_bot()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_F_iso_bot_l_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     double F_iso_bot_l;
     if (! PyArg_ParseTuple(args, "id", &i_deriv, &F_iso_bot_l))
          return NULL;
     r = xrtm_set_F_iso_bot_l_1(d, i_deriv, F_iso_bot_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_bot_l_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_F_iso_bot_l_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *F_iso_bot_l_object  = NULL;
     PyObject *F_iso_bot_l_ndarray = NULL;
     double *F_iso_bot_l;
     if (! PyArg_ParseTuple(args, "O", &F_iso_bot_l_object))
          return NULL;
     F_iso_bot_l_ndarray = PyArray_FROM_OTF(F_iso_bot_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (F_iso_bot_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(F_iso_bot_l_ndarray, "F_iso_bot_l", 1, d->n_derivs) < 0)
          return NULL;
     F_iso_bot_l = (double *) array_from_ndarray(F_iso_bot_l_ndarray, 8);
     r = xrtm_set_F_iso_bot_l_n(d, F_iso_bot_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_iso_bot_l_n()");
          return NULL;
     }
     Py_DECREF(F_iso_bot_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_F_iso_bot_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "i", &i_deriv))
          return NULL;
     r = xrtm_get_F_iso_bot_l(d, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_F_iso_bot_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_F_0_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double F_0;
     if (! PyArg_ParseTuple(args, "d", &F_0))
          return NULL;
     r = xrtm_set_F_0(d, F_0);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_F_0()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_F_0_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_F_0(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_F_0()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_theta_0_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double theta_0;
     if (! PyArg_ParseTuple(args, "d", &theta_0))
          return NULL;
     r = xrtm_set_theta_0(d, theta_0);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_theta_0()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_theta_0_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_theta_0(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_theta_0()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_phi_0_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double phi_0;
     if (! PyArg_ParseTuple(args, "d", &phi_0))
          return NULL;
     r = xrtm_set_phi_0(d, phi_0);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_phi_0()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_phi_0_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_phi_0(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_phi_0()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_levels_b_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *levels_b_object  = NULL;
     PyObject *levels_b_ndarray = NULL;
     double *levels_b;
     if (! PyArg_ParseTuple(args, "O", &levels_b_object))
          return NULL;
     levels_b_ndarray = PyArray_FROM_OTF(levels_b_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (levels_b_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(levels_b_ndarray, "levels_b", 1, d->n_out_levels) < 0)
          return NULL;
     levels_b = (double *) array_from_ndarray(levels_b_ndarray, 8);
     r = xrtm_set_levels_b(d, levels_b);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_levels_b()");
          return NULL;
     }
     Py_DECREF(levels_b_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_levels_b_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *levels_b_ndarray = NULL;
     double *levels_b;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_out_levels;
     levels_b_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (levels_b_ndarray == NULL)
          return NULL;
     levels_b = (double *) array_from_ndarray(levels_b_ndarray, 8);
     r = xrtm_get_levels_b(d, levels_b);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_levels_b()");
          return NULL;
     }
     return Py_BuildValue("O", levels_b_ndarray);
}


static PyObject *xrtm_set_levels_b_l_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     PyObject *levels_b_l_object  = NULL;
     PyObject *levels_b_l_ndarray = NULL;
     double *levels_b_l;
     if (! PyArg_ParseTuple(args, "iO", &i_deriv, &levels_b_l_object))
          return NULL;
     levels_b_l_ndarray = PyArray_FROM_OTF(levels_b_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (levels_b_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(levels_b_l_ndarray, "levels_b_l", 1, d->n_derivs) < 0)
          return NULL;
     levels_b_l = (double *) array_from_ndarray(levels_b_l_ndarray, 8);
     r = xrtm_set_levels_b_l_1(d, i_deriv, levels_b_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_levels_b_l_1()");
          return NULL;
     }
     Py_DECREF(levels_b_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_levels_b_l_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *levels_b_l_object  = NULL;
     PyObject *levels_b_l_ndarray = NULL;
     double **levels_b_l;
     if (! PyArg_ParseTuple(args, "O", &levels_b_l_object))
          return NULL;
     levels_b_l_ndarray = PyArray_FROM_OTF(levels_b_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (levels_b_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(levels_b_l_ndarray, "levels_b_l", 2, d->n_out_levels, d->n_derivs) < 0)
          return NULL;
     levels_b_l = (double **) array_from_ndarray(levels_b_l_ndarray, 8);
     r = xrtm_set_levels_b_l_n(d, levels_b_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_levels_b_l_n()");
          return NULL;
     }
     Py_DECREF(levels_b_l_ndarray);
     free_array(levels_b_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_levels_b_l_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     npy_intp dims[1];
     PyObject *levels_b_l_ndarray = NULL;
     double *levels_b_l;
     if (! PyArg_ParseTuple(args, "i", &i_deriv))
          return NULL;
     dims[0] = d->n_out_levels;
     levels_b_l_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (levels_b_l_ndarray == NULL)
          return NULL;
     levels_b_l = (double *) array_from_ndarray(levels_b_l_ndarray, 8);
     r = xrtm_get_levels_b_l(d, i_deriv, levels_b_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_levels_b_l()");
          return NULL;
     }
     return Py_BuildValue("O", levels_b_l_ndarray);
}


static PyObject *xrtm_set_surface_b_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     double surface_b;
     if (! PyArg_ParseTuple(args, "d", &surface_b))
          return NULL;
     r = xrtm_set_surface_b(d, surface_b);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_surface_b()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_surface_b_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_get_surface_b(d);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_surface_b()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_surface_b_l_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     double surface_b_l;
     if (! PyArg_ParseTuple(args, "id", &i_deriv, &surface_b_l))
          return NULL;
     r = xrtm_set_surface_b_l_1(d, i_deriv, surface_b_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_surface_b_l_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_surface_b_l_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *surface_b_l_object  = NULL;
     PyObject *surface_b_l_ndarray = NULL;
     double *surface_b_l;
     if (! PyArg_ParseTuple(args, "O", &surface_b_l_object))
          return NULL;
     surface_b_l_ndarray = PyArray_FROM_OTF(surface_b_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (surface_b_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(surface_b_l_ndarray, "surface_b_l", 1, d->n_derivs) < 0)
          return NULL;
     surface_b_l = (double *) array_from_ndarray(surface_b_l_ndarray, 8);
     r = xrtm_set_surface_b_l_n(d, surface_b_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_surface_b_l_n()");
          return NULL;
     }
     Py_DECREF(surface_b_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_surface_b_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "i", &i_deriv))
          return NULL;
     r = xrtm_get_surface_b_l(d, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_surface_b_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_g_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     double g;
     if (! PyArg_ParseTuple(args, "id", &i_layer, &g))
          return NULL;
     r = xrtm_set_g_1(d, i_layer, g);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_g_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *g_object  = NULL;
     PyObject *g_ndarray = NULL;
     double *g;
     if (! PyArg_ParseTuple(args, "O", &g_object))
          return NULL;
     g_ndarray = PyArray_FROM_OTF(g_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (g_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(g_ndarray, "g", 1, d->n_layers) < 0)
          return NULL;
     g = (double *) array_from_ndarray(g_ndarray, 8);
     r = xrtm_set_g_n(d, g);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_n()");
          return NULL;
     }
     Py_DECREF(g_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_g_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     if (! PyArg_ParseTuple(args, "i", &i_layer))
          return NULL;
     r = xrtm_get_g(d, i_layer);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_g()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_g_l_11_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     double g_l;
     if (! PyArg_ParseTuple(args, "iid", &i_layer, &i_deriv, &g_l))
          return NULL;
     r = xrtm_set_g_l_11(d, i_layer, i_deriv, g_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_l_11()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_g_l_n1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     PyObject *g_l_object  = NULL;
     PyObject *g_l_ndarray = NULL;
     double *g_l;
     if (! PyArg_ParseTuple(args, "iO", &i_deriv, &g_l_object))
          return NULL;
     g_l_ndarray = PyArray_FROM_OTF(g_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (g_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(g_l_ndarray, "g_l", 1, d->n_layers) < 0)
          return NULL;
     g_l = (double *) array_from_ndarray(g_l_ndarray, 8);
     r = xrtm_set_g_l_n1(d, i_deriv, g_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_l_n1()");
          return NULL;
     }
     Py_DECREF(g_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_g_l_1n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     PyObject *g_l_object  = NULL;
     PyObject *g_l_ndarray = NULL;
     double *g_l;
     if (! PyArg_ParseTuple(args, "iO", &i_layer, &g_l_object))
          return NULL;
     g_l_ndarray = PyArray_FROM_OTF(g_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (g_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(g_l_ndarray, "g_l", 1, d->n_derivs) < 0)
          return NULL;
     g_l = (double *) array_from_ndarray(g_l_ndarray, 8);
     r = xrtm_set_g_l_1n(d, i_layer, g_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_l_1n()");
          return NULL;
     }
     Py_DECREF(g_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_g_l_nn_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *g_l_object  = NULL;
     PyObject *g_l_ndarray = NULL;
     double **g_l;
     if (! PyArg_ParseTuple(args, "O", &g_l_object))
          return NULL;
     g_l_ndarray = PyArray_FROM_OTF(g_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (g_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(g_l_ndarray, "g_l", 2, d->n_layers, d->n_derivs) < 0)
          return NULL;
     g_l = (double **) array_from_ndarray(g_l_ndarray, 8);
     r = xrtm_set_g_l_nn(d, g_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_g_l_nn()");
          return NULL;
     }
     Py_DECREF(g_l_ndarray);
     free_array(g_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_g_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "ii", &i_layer, &i_deriv))
          return NULL;
     r = xrtm_get_g_l(d, i_layer, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_g_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_coef_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int n_coef_layer;
     PyObject *coef_object  = NULL;
     PyObject *coef_ndarray = NULL;
     double **coef;
     if (! PyArg_ParseTuple(args, "iiO", &i_layer, &n_coef_layer, &coef_object))
          return NULL;
     coef_ndarray = PyArray_FROM_OTF(coef_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_ndarray, "coef", 2, d->n_elem, n_coef_layer) < 0)
          return NULL;
     coef = (double **) array_from_ndarray(coef_ndarray, 8);
     r = xrtm_set_coef_1(d, i_layer, n_coef_layer, coef);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_1()");
          return NULL;
     }
     Py_DECREF(coef_ndarray);
     free_array(coef, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_coef_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *n_coef_layer_object  = NULL;
     PyObject *n_coef_layer_ndarray = NULL;
     int *n_coef_layer;
     PyObject *coef_object  = NULL;
     PyObject *coef_ndarray = NULL;
     double ***coef;
     if (! PyArg_ParseTuple(args, "OO", &n_coef_layer_object, &coef_object))
          return NULL;
     n_coef_layer_ndarray = PyArray_FROM_OTF(n_coef_layer_object, NPY_INT, NPY_ARRAY_IN_ARRAY);
     if (n_coef_layer_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(n_coef_layer_ndarray, "n_coef_layer", 1, d->n_layers) < 0)
          return NULL;
     n_coef_layer = (int *) array_from_ndarray(n_coef_layer_ndarray, 4);
     coef_ndarray = PyArray_FROM_OTF(coef_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_ndarray, "coef", 3, d->n_layers, d->n_elem, d->n_coef) < 0)
          return NULL;
     coef = (double ***) array_from_ndarray(coef_ndarray, 8);
     r = xrtm_set_coef_n(d, n_coef_layer, coef);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_n()");
          return NULL;
     }
     Py_DECREF(n_coef_layer_ndarray);
     Py_DECREF(coef_ndarray);
     free_array(coef, 3);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_n_coef_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     if (! PyArg_ParseTuple(args, "i", &i_layer))
          return NULL;
     r = xrtm_get_n_coef(d, i_layer);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_n_coef()");
          return NULL;
     }
     return Py_BuildValue("i", r);
}


static PyObject *xrtm_get_coef_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_elem;
     int i_coef;
     if (! PyArg_ParseTuple(args, "iii", &i_layer, &i_elem, &i_coef))
          return NULL;
     r = xrtm_get_coef(d, i_layer, i_elem, i_coef);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_coef()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_coef_l_11_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     PyObject *coef_l_object  = NULL;
     PyObject *coef_l_ndarray = NULL;
     double **coef_l;
     if (! PyArg_ParseTuple(args, "iiO", &i_layer, &i_deriv, &coef_l_object))
          return NULL;
     coef_l_ndarray = PyArray_FROM_OTF(coef_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_l_ndarray, "coef_l", 2, d->n_elem, d->n_coef_layer[i_layer]) < 0)
          return NULL;
     coef_l = (double **) array_from_ndarray(coef_l_ndarray, 8);
     r = xrtm_set_coef_l_11(d, i_layer, i_deriv, coef_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_l_11()");
          return NULL;
     }
     Py_DECREF(coef_l_ndarray);
     free_array(coef_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_coef_l_n1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     PyObject *coef_l_object  = NULL;
     PyObject *coef_l_ndarray = NULL;
     double ***coef_l;
     if (! PyArg_ParseTuple(args, "iO", &i_deriv, &coef_l_object))
          return NULL;
     coef_l_ndarray = PyArray_FROM_OTF(coef_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_l_ndarray, "coef_l", 3, d->n_layers, d->n_elem, d->n_coef) < 0)
          return NULL;
     coef_l = (double ***) array_from_ndarray(coef_l_ndarray, 8);
     r = xrtm_set_coef_l_n1(d, i_deriv, coef_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_l_n1()");
          return NULL;
     }
     Py_DECREF(coef_l_ndarray);
     free_array(coef_l, 3);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_coef_l_1n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     PyObject *coef_l_object  = NULL;
     PyObject *coef_l_ndarray = NULL;
     double ***coef_l;
     if (! PyArg_ParseTuple(args, "iO", &i_layer, &coef_l_object))
          return NULL;
     coef_l_ndarray = PyArray_FROM_OTF(coef_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_l_ndarray, "coef_l", 3, d->n_derivs, d->n_elem, d->n_coef_layer[i_layer]) < 0)
          return NULL;
     coef_l = (double ***) array_from_ndarray(coef_l_ndarray, 8);
     r = xrtm_set_coef_l_1n(d, i_layer, coef_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_l_1n()");
          return NULL;
     }
     Py_DECREF(coef_l_ndarray);
     free_array(coef_l, 3);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_coef_l_nn_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *coef_l_object  = NULL;
     PyObject *coef_l_ndarray = NULL;
     double ****coef_l;
     if (! PyArg_ParseTuple(args, "O", &coef_l_object))
          return NULL;
     coef_l_ndarray = PyArray_FROM_OTF(coef_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (coef_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(coef_l_ndarray, "coef_l", 4, d->n_layers, d->n_derivs, d->n_elem, d->n_coef) < 0)
          return NULL;
     coef_l = (double ****) array_from_ndarray(coef_l_ndarray, 8);
     r = xrtm_set_coef_l_nn(d, coef_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_coef_l_nn()");
          return NULL;
     }
     Py_DECREF(coef_l_ndarray);
     free_array(coef_l, 4);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_coef_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     int i_elem;
     int i_coef;
     if (! PyArg_ParseTuple(args, "iiii", &i_layer, &i_deriv, &i_elem, &i_coef))
          return NULL;
     r = xrtm_get_coef_l(d, i_layer, i_deriv, i_elem, i_coef);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_coef_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_omega_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     double omega;
     if (! PyArg_ParseTuple(args, "id", &i_layer, &omega))
          return NULL;
     r = xrtm_set_omega_1(d, i_layer, omega);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_omega_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *omega_object  = NULL;
     PyObject *omega_ndarray = NULL;
     double *omega;
     if (! PyArg_ParseTuple(args, "O", &omega_object))
          return NULL;
     omega_ndarray = PyArray_FROM_OTF(omega_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (omega_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(omega_ndarray, "omega", 1, d->n_layers) < 0)
          return NULL;
     omega = (double *) array_from_ndarray(omega_ndarray, 8);
     r = xrtm_set_omega_n(d, omega);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_n()");
          return NULL;
     }
     Py_DECREF(omega_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_omega_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     if (! PyArg_ParseTuple(args, "i", &i_layer))
          return NULL;
     r = xrtm_get_omega(d, i_layer);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_omega()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_omega_l_11_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     double omega_l;
     if (! PyArg_ParseTuple(args, "iid", &i_layer, &i_deriv, &omega_l))
          return NULL;
     r = xrtm_set_omega_l_11(d, i_layer, i_deriv, omega_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_l_11()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_omega_l_n1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     PyObject *omega_l_object  = NULL;
     PyObject *omega_l_ndarray = NULL;
     double *omega_l;
     if (! PyArg_ParseTuple(args, "iO", &i_deriv, &omega_l_object))
          return NULL;
     omega_l_ndarray = PyArray_FROM_OTF(omega_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (omega_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(omega_l_ndarray, "omega_l", 1, d->n_layers) < 0)
          return NULL;
     omega_l = (double *) array_from_ndarray(omega_l_ndarray, 8);
     r = xrtm_set_omega_l_n1(d, i_deriv, omega_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_l_n1()");
          return NULL;
     }
     Py_DECREF(omega_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_omega_l_1n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     PyObject *omega_l_object  = NULL;
     PyObject *omega_l_ndarray = NULL;
     double *omega_l;
     if (! PyArg_ParseTuple(args, "iO", &i_layer, &omega_l_object))
          return NULL;
     omega_l_ndarray = PyArray_FROM_OTF(omega_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (omega_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(omega_l_ndarray, "omega_l", 1, d->n_derivs) < 0)
          return NULL;
     omega_l = (double *) array_from_ndarray(omega_l_ndarray, 8);
     r = xrtm_set_omega_l_1n(d, i_layer, omega_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_l_1n()");
          return NULL;
     }
     Py_DECREF(omega_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_omega_l_nn_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *omega_l_object  = NULL;
     PyObject *omega_l_ndarray = NULL;
     double **omega_l;
     if (! PyArg_ParseTuple(args, "O", &omega_l_object))
          return NULL;
     omega_l_ndarray = PyArray_FROM_OTF(omega_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (omega_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(omega_l_ndarray, "omega_l", 2, d->n_layers, d->n_derivs) < 0)
          return NULL;
     omega_l = (double **) array_from_ndarray(omega_l_ndarray, 8);
     r = xrtm_set_omega_l_nn(d, omega_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_omega_l_nn()");
          return NULL;
     }
     Py_DECREF(omega_l_ndarray);
     free_array(omega_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_omega_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "ii", &i_layer, &i_deriv))
          return NULL;
     r = xrtm_get_omega_l(d, i_layer, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_omega_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_ltau_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     double ltau;
     if (! PyArg_ParseTuple(args, "id", &i_layer, &ltau))
          return NULL;
     r = xrtm_set_ltau_1(d, i_layer, ltau);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_ltau_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *ltau_object  = NULL;
     PyObject *ltau_ndarray = NULL;
     double *ltau;
     if (! PyArg_ParseTuple(args, "O", &ltau_object))
          return NULL;
     ltau_ndarray = PyArray_FROM_OTF(ltau_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (ltau_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(ltau_ndarray, "ltau", 1, d->n_layers) < 0)
          return NULL;
     ltau = (double *) array_from_ndarray(ltau_ndarray, 8);
     r = xrtm_set_ltau_n(d, ltau);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_n()");
          return NULL;
     }
     Py_DECREF(ltau_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_ltau_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     if (! PyArg_ParseTuple(args, "i", &i_layer))
          return NULL;
     r = xrtm_get_ltau(d, i_layer);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_ltau()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_ltau_l_11_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     double ltau_l;
     if (! PyArg_ParseTuple(args, "iid", &i_layer, &i_deriv, &ltau_l))
          return NULL;
     r = xrtm_set_ltau_l_11(d, i_layer, i_deriv, ltau_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_l_11()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_ltau_l_n1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_deriv;
     PyObject *ltau_l_object  = NULL;
     PyObject *ltau_l_ndarray = NULL;
     double *ltau_l;
     if (! PyArg_ParseTuple(args, "iO", &i_deriv, &ltau_l_object))
          return NULL;
     ltau_l_ndarray = PyArray_FROM_OTF(ltau_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (ltau_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(ltau_l_ndarray, "ltau_l", 1, d->n_layers) < 0)
          return NULL;
     ltau_l = (double *) array_from_ndarray(ltau_l_ndarray, 8);
     r = xrtm_set_ltau_l_n1(d, i_deriv, ltau_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_l_n1()");
          return NULL;
     }
     Py_DECREF(ltau_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_ltau_l_1n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     PyObject *ltau_l_object  = NULL;
     PyObject *ltau_l_ndarray = NULL;
     double *ltau_l;
     if (! PyArg_ParseTuple(args, "iO", &i_layer, &ltau_l_object))
          return NULL;
     ltau_l_ndarray = PyArray_FROM_OTF(ltau_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (ltau_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(ltau_l_ndarray, "ltau_l", 1, d->n_derivs) < 0)
          return NULL;
     ltau_l = (double *) array_from_ndarray(ltau_l_ndarray, 8);
     r = xrtm_set_ltau_l_1n(d, i_layer, ltau_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_l_1n()");
          return NULL;
     }
     Py_DECREF(ltau_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_ltau_l_nn_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     PyObject *ltau_l_object  = NULL;
     PyObject *ltau_l_ndarray = NULL;
     double **ltau_l;
     if (! PyArg_ParseTuple(args, "O", &ltau_l_object))
          return NULL;
     ltau_l_ndarray = PyArray_FROM_OTF(ltau_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (ltau_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(ltau_l_ndarray, "ltau_l", 2, d->n_layers, d->n_derivs) < 0)
          return NULL;
     ltau_l = (double **) array_from_ndarray(ltau_l_ndarray, 8);
     r = xrtm_set_ltau_l_nn(d, ltau_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_ltau_l_nn()");
          return NULL;
     }
     Py_DECREF(ltau_l_ndarray);
     free_array(ltau_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_ltau_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_layer;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "ii", &i_layer, &i_deriv))
          return NULL;
     r = xrtm_get_ltau_l(d, i_layer, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_ltau_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_kernel_ampfac_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     double ampfac;
     if (! PyArg_ParseTuple(args, "id", &i_kernel, &ampfac))
          return NULL;
     r = xrtm_set_kernel_ampfac(d, i_kernel, ampfac);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_ampfac()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_kernel_ampfac_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     if (! PyArg_ParseTuple(args, "i", &i_kernel))
          return NULL;
     r = xrtm_get_kernel_ampfac(d, i_kernel);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_kernel_ampfac()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_kernel_params_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_param;
     double param;
     if (! PyArg_ParseTuple(args, "iid", &i_kernel, &i_param, &param))
          return NULL;
     r = xrtm_set_kernel_params_1(d, i_kernel, i_param, param);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_kernel_params_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     PyObject *params_object  = NULL;
     PyObject *params_ndarray = NULL;
     double *params;
     if (! PyArg_ParseTuple(args, "iO", &i_kernel, &params_object))
          return NULL;
     params_ndarray = PyArray_FROM_OTF(params_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (params_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(params_ndarray, "params", 1, kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel])) < 0)
          return NULL;
     params = (double *) array_from_ndarray(params_ndarray, 8);
     r = xrtm_set_kernel_params_n(d, i_kernel, params);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_n()");
          return NULL;
     }
     Py_DECREF(params_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_kernel_params_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_param;
     if (! PyArg_ParseTuple(args, "ii", &i_kernel, &i_param))
          return NULL;
     r = xrtm_get_kernel_params(d, i_kernel, i_param);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_kernel_params()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_kernel_ampfac_l_1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_deriv;
     double ampfac_l;
     if (! PyArg_ParseTuple(args, "iid", &i_kernel, &i_deriv, &ampfac_l))
          return NULL;
     r = xrtm_set_kernel_ampfac_l_1(d, i_kernel, i_deriv, ampfac_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_ampfac_l_1()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_kernel_ampfac_l_n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     PyObject *ampfac_l_object  = NULL;
     PyObject *ampfac_l_ndarray = NULL;
     double *ampfac_l;
     if (! PyArg_ParseTuple(args, "iO", &i_kernel, &ampfac_l_object))
          return NULL;
     ampfac_l_ndarray = PyArray_FROM_OTF(ampfac_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (ampfac_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(ampfac_l_ndarray, "ampfac_l", 1, d->n_derivs) < 0)
          return NULL;
     ampfac_l = (double *) array_from_ndarray(ampfac_l_ndarray, 8);
     r = xrtm_set_kernel_ampfac_l_n(d, i_kernel, ampfac_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_ampfac_l_n()");
          return NULL;
     }
     Py_DECREF(ampfac_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_kernel_ampfac_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_deriv;
     if (! PyArg_ParseTuple(args, "ii", &i_kernel, &i_deriv))
          return NULL;
     r = xrtm_get_kernel_ampfac_l(d, i_kernel, i_deriv);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_kernel_ampfac_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_set_kernel_params_l_11_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_deriv;
     int i_param;
     double param_l;
     if (! PyArg_ParseTuple(args, "iiid", &i_kernel, &i_deriv, &i_param, &param_l))
          return NULL;
     r = xrtm_set_kernel_params_l_11(d, i_kernel, i_deriv, i_param, param_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_l_11()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_kernel_params_l_1n_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_deriv;
     PyObject *params_l_object  = NULL;
     PyObject *params_l_ndarray = NULL;
     double *params_l;
     if (! PyArg_ParseTuple(args, "iiO", &i_kernel, &i_deriv, &params_l_object))
          return NULL;
     params_l_ndarray = PyArray_FROM_OTF(params_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (params_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(params_l_ndarray, "params_l", 1, kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel])) < 0)
          return NULL;
     params_l = (double *) array_from_ndarray(params_l_ndarray, 8);
     r = xrtm_set_kernel_params_l_1n(d, i_kernel, i_deriv, params_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_l_1n()");
          return NULL;
     }
     Py_DECREF(params_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_kernel_params_l_n1_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_param;
     PyObject *params_l_object  = NULL;
     PyObject *params_l_ndarray = NULL;
     double *params_l;
     if (! PyArg_ParseTuple(args, "iiO", &i_kernel, &i_param, &params_l_object))
          return NULL;
     params_l_ndarray = PyArray_FROM_OTF(params_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (params_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(params_l_ndarray, "params_l", 1, d->n_derivs) < 0)
          return NULL;
     params_l = (double *) array_from_ndarray(params_l_ndarray, 8);
     r = xrtm_set_kernel_params_l_n1(d, i_kernel, i_param, params_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_l_n1()");
          return NULL;
     }
     Py_DECREF(params_l_ndarray);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_set_kernel_params_l_nn_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     PyObject *params_l_object  = NULL;
     PyObject *params_l_ndarray = NULL;
     double **params_l;
     if (! PyArg_ParseTuple(args, "iO", &i_kernel, &params_l_object))
          return NULL;
     params_l_ndarray = PyArray_FROM_OTF(params_l_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (params_l_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(params_l_ndarray, "params_l", 2, d->n_derivs, kernel_n_params((enum xrtm_kernel_type) d->kernels[i_kernel])) < 0)
          return NULL;
     params_l = (double **) array_from_ndarray(params_l_ndarray, 8);
     r = xrtm_set_kernel_params_l_nn(d, i_kernel, params_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_set_kernel_params_l_nn()");
          return NULL;
     }
     Py_DECREF(params_l_ndarray);
     free_array(params_l, 2);
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_get_kernel_params_l_py(xrtm_data_py *self, PyObject *args)
{
     double r;
     xrtm_data *d = &self->xrtm;
     int i_kernel;
     int i_deriv;
     int i_param;
     if (! PyArg_ParseTuple(args, "iii", &i_kernel, &i_deriv, &i_param))
          return NULL;
     r = xrtm_get_kernel_params_l(d, i_kernel, i_deriv, i_param);
     if (r == XRTM_DBL_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_get_kernel_params_l()");
          return NULL;
     }
     return Py_BuildValue("d", r);
}


static PyObject *xrtm_update_varied_layers_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     r = xrtm_update_varied_layers(d);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_update_varied_layers()");
          return NULL;
     }
     return Py_BuildValue("i",  0);
}


static PyObject *xrtm_qx_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *qx_ndarray = NULL;
     double *qx;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_quad;
     qx_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (qx_ndarray == NULL)
          return NULL;
     qx = (double *) array_from_ndarray(qx_ndarray, 8);
     r = xrtm_qx(d, qx);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_qx()");
          return NULL;
     }
     return Py_BuildValue("O", qx_ndarray);
}


static PyObject *xrtm_qw_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *qw_ndarray = NULL;
     double *qw;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_quad;
     qw_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (qw_ndarray == NULL)
          return NULL;
     qw = (double *) array_from_ndarray(qw_ndarray, 8);
     r = xrtm_qw(d, qw);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_qw()");
          return NULL;
     }
     return Py_BuildValue("O", qw_ndarray);
}


static PyObject *xrtm_kernel_qx_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *kernel_qx_ndarray = NULL;
     double *kernel_qx;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_kernel_quad;
     kernel_qx_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (kernel_qx_ndarray == NULL)
          return NULL;
     kernel_qx = (double *) array_from_ndarray(kernel_qx_ndarray, 8);
     r = xrtm_kernel_qx(d, kernel_qx);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_kernel_qx()");
          return NULL;
     }
     return Py_BuildValue("O", kernel_qx_ndarray);
}


static PyObject *xrtm_kernel_qw_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     npy_intp dims[1];
     PyObject *kernel_qw_ndarray = NULL;
     double *kernel_qw;
     if (! PyArg_ParseTuple(args, ""))
          return NULL;
     dims[0] = d->n_kernel_quad;
     kernel_qw_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (kernel_qw_ndarray == NULL)
          return NULL;
     kernel_qw = (double *) array_from_ndarray(kernel_qw_ndarray, 8);
     r = xrtm_kernel_qw(d, kernel_qw);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_kernel_qw()");
          return NULL;
     }
     return Py_BuildValue("O", kernel_qw_ndarray);
}


static PyObject *xrtm_solution_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     enum xrtm_solver_mask solver;
     const char *solver_string = NULL;
     int solutions;
     int n_out_phis;
     PyObject *out_phis_object  = NULL;
     PyObject *out_phis_ndarray = NULL;
     double **out_phis;
     npy_intp dims[5];
     PyObject *I_p_ndarray = NULL;
     double ****I_p;
     PyObject *I_m_ndarray = NULL;
     double ****I_m;
     PyObject *K_p_ndarray = NULL;
     double *****K_p;
     PyObject *K_m_ndarray = NULL;
     double *****K_m;
     PyObject *mean_p_ndarray = NULL;
     double *mean_p;
     PyObject *mean_m_ndarray = NULL;
     double *mean_m;
     PyObject *mean_p_l_ndarray = NULL;
     double **mean_p_l;
     PyObject *mean_m_l_ndarray = NULL;
     double **mean_m_l;
     PyObject *flux_p_ndarray = NULL;
     double *flux_p;
     PyObject *flux_m_ndarray = NULL;
     double *flux_m;
     PyObject *flux_p_l_ndarray = NULL;
     double **flux_p_l;
     PyObject *flux_m_l_ndarray = NULL;
     double **flux_m_l;
     PyObject *flux_div_ndarray = NULL;
     double *flux_div;
     PyObject *flux_div_l_ndarray = NULL;
     double **flux_div_l;
     if (! PyArg_ParseTuple(args, "siiO", &solver_string, &solutions, &n_out_phis, &out_phis_object))
          return NULL;
     solver = xrtm_solver_name_to_mask(solver_string);
     if ((int) solver < 0) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solver_name_to_mask()");
          return NULL;
     }
     out_phis_ndarray = PyArray_FROM_OTF(out_phis_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (out_phis_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(out_phis_ndarray, "out_phis", 2, d->n_out_thetas, n_out_phis) < 0)
          return NULL;
     out_phis = (double **) array_from_ndarray(out_phis_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_out_thetas_2;
     dims[2] = n_out_phis;
     dims[3] = d->n_stokes;
     I_p_ndarray = PyArray_SimpleNew(4, dims, NPY_DOUBLE);
     if (I_p_ndarray == NULL)
          return NULL;
     I_p = (double ****) array_from_ndarray(I_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_out_thetas_2;
     dims[2] = n_out_phis;
     dims[3] = d->n_stokes;
     I_m_ndarray = PyArray_SimpleNew(4, dims, NPY_DOUBLE);
     if (I_m_ndarray == NULL)
          return NULL;
     I_m = (double ****) array_from_ndarray(I_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     dims[2] = d->n_out_thetas_2;
     dims[3] = n_out_phis;
     dims[4] = d->n_stokes;
     K_p_ndarray = PyArray_SimpleNew(5, dims, NPY_DOUBLE);
     if (K_p_ndarray == NULL)
          return NULL;
     K_p = (double *****) array_from_ndarray(K_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     dims[2] = d->n_out_thetas_2;
     dims[3] = n_out_phis;
     dims[4] = d->n_stokes;
     K_m_ndarray = PyArray_SimpleNew(5, dims, NPY_DOUBLE);
     if (K_m_ndarray == NULL)
          return NULL;
     K_m = (double *****) array_from_ndarray(K_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     mean_p_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (mean_p_ndarray == NULL)
          return NULL;
     mean_p = (double *) array_from_ndarray(mean_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     mean_m_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (mean_m_ndarray == NULL)
          return NULL;
     mean_m = (double *) array_from_ndarray(mean_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     mean_p_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (mean_p_l_ndarray == NULL)
          return NULL;
     mean_p_l = (double **) array_from_ndarray(mean_p_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     mean_m_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (mean_m_l_ndarray == NULL)
          return NULL;
     mean_m_l = (double **) array_from_ndarray(mean_m_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     flux_p_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_p_ndarray == NULL)
          return NULL;
     flux_p = (double *) array_from_ndarray(flux_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     flux_m_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_m_ndarray == NULL)
          return NULL;
     flux_m = (double *) array_from_ndarray(flux_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_p_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_p_l_ndarray == NULL)
          return NULL;
     flux_p_l = (double **) array_from_ndarray(flux_p_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_m_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_m_l_ndarray == NULL)
          return NULL;
     flux_m_l = (double **) array_from_ndarray(flux_m_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     flux_div_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_div_ndarray == NULL)
          return NULL;
     flux_div = (double *) array_from_ndarray(flux_div_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_div_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_div_l_ndarray == NULL)
          return NULL;
     flux_div_l = (double **) array_from_ndarray(flux_div_l_ndarray, 8);
     r = xrtm_solution(d, (enum xrtm_solver_mask) solver, solutions, n_out_phis, out_phis, I_p, I_m, K_p, K_m, mean_p, mean_m, mean_p_l, mean_m_l, flux_p, flux_m, flux_p_l, flux_m_l, flux_div, flux_div_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solution()");
          return NULL;
     }
     Py_DECREF(out_phis_ndarray);
     free_array(out_phis, 2);
     free_array(I_p, 4);
     free_array(I_m, 4);
     free_array(K_p, 5);
     free_array(K_m, 5);
     free_array(mean_p_l, 2);
     free_array(mean_m_l, 2);
     free_array(flux_p_l, 2);
     free_array(flux_m_l, 2);
     free_array(flux_div_l, 2);
     return Py_BuildValue("OOOOOOOOOOOOOO", I_p_ndarray, I_m_ndarray, K_p_ndarray, K_m_ndarray, mean_p_ndarray, mean_m_ndarray, mean_p_l_ndarray, mean_m_l_ndarray, flux_p_ndarray, flux_m_ndarray, flux_p_l_ndarray, flux_m_l_ndarray, flux_div_ndarray, flux_div_l_ndarray);
}


static PyObject *xrtm_radiance_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     enum xrtm_solver_mask solver;
     const char *solver_string = NULL;
     int n_out_phis;
     PyObject *out_phis_object  = NULL;
     PyObject *out_phis_ndarray = NULL;
     double **out_phis;
     npy_intp dims[5];
     PyObject *I_p_ndarray = NULL;
     double ****I_p;
     PyObject *I_m_ndarray = NULL;
     double ****I_m;
     PyObject *K_p_ndarray = NULL;
     double *****K_p;
     PyObject *K_m_ndarray = NULL;
     double *****K_m;
     if (! PyArg_ParseTuple(args, "siO", &solver_string, &n_out_phis, &out_phis_object))
          return NULL;
     solver = xrtm_solver_name_to_mask(solver_string);
     if ((int) solver < 0) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solver_name_to_mask()");
          return NULL;
     }
     out_phis_ndarray = PyArray_FROM_OTF(out_phis_object, NPY_DOUBLE, NPY_ARRAY_IN_ARRAY);
     if (out_phis_ndarray == NULL)
          return NULL;
     if (check_pyarray_shape(out_phis_ndarray, "out_phis", 2, d->n_out_thetas, n_out_phis) < 0)
          return NULL;
     out_phis = (double **) array_from_ndarray(out_phis_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_out_thetas_2;
     dims[2] = n_out_phis;
     dims[3] = d->n_stokes;
     I_p_ndarray = PyArray_SimpleNew(4, dims, NPY_DOUBLE);
     if (I_p_ndarray == NULL)
          return NULL;
     I_p = (double ****) array_from_ndarray(I_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_out_thetas_2;
     dims[2] = n_out_phis;
     dims[3] = d->n_stokes;
     I_m_ndarray = PyArray_SimpleNew(4, dims, NPY_DOUBLE);
     if (I_m_ndarray == NULL)
          return NULL;
     I_m = (double ****) array_from_ndarray(I_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     dims[2] = d->n_out_thetas_2;
     dims[3] = n_out_phis;
     dims[4] = d->n_stokes;
     K_p_ndarray = PyArray_SimpleNew(5, dims, NPY_DOUBLE);
     if (K_p_ndarray == NULL)
          return NULL;
     K_p = (double *****) array_from_ndarray(K_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     dims[2] = d->n_out_thetas_2;
     dims[3] = n_out_phis;
     dims[4] = d->n_stokes;
     K_m_ndarray = PyArray_SimpleNew(5, dims, NPY_DOUBLE);
     if (K_m_ndarray == NULL)
          return NULL;
     K_m = (double *****) array_from_ndarray(K_m_ndarray, 8);
     r = xrtm_radiance(d, (enum xrtm_solver_mask) solver, n_out_phis, out_phis, I_p, I_m, K_p, K_m);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_radiance()");
          return NULL;
     }
     Py_DECREF(out_phis_ndarray);
     free_array(out_phis, 2);
     free_array(I_p, 4);
     free_array(I_m, 4);
     free_array(K_p, 5);
     free_array(K_m, 5);
     return Py_BuildValue("OOOO", I_p_ndarray, I_m_ndarray, K_p_ndarray, K_m_ndarray);
}


static PyObject *xrtm_mean_radiance_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     enum xrtm_solver_mask solver;
     const char *solver_string = NULL;
     npy_intp dims[2];
     PyObject *mean_p_ndarray = NULL;
     double *mean_p;
     PyObject *mean_m_ndarray = NULL;
     double *mean_m;
     PyObject *mean_p_l_ndarray = NULL;
     double **mean_p_l;
     PyObject *mean_m_l_ndarray = NULL;
     double **mean_m_l;
     if (! PyArg_ParseTuple(args, "s", &solver_string))
          return NULL;
     solver = xrtm_solver_name_to_mask(solver_string);
     if ((int) solver < 0) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solver_name_to_mask()");
          return NULL;
     }
     dims[0] = d->n_out_levels;
     mean_p_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (mean_p_ndarray == NULL)
          return NULL;
     mean_p = (double *) array_from_ndarray(mean_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     mean_m_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (mean_m_ndarray == NULL)
          return NULL;
     mean_m = (double *) array_from_ndarray(mean_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     mean_p_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (mean_p_l_ndarray == NULL)
          return NULL;
     mean_p_l = (double **) array_from_ndarray(mean_p_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     mean_m_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (mean_m_l_ndarray == NULL)
          return NULL;
     mean_m_l = (double **) array_from_ndarray(mean_m_l_ndarray, 8);
     r = xrtm_mean_radiance(d, (enum xrtm_solver_mask) solver, mean_p, mean_m, mean_p_l, mean_m_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_mean_radiance()");
          return NULL;
     }
     free_array(mean_p_l, 2);
     free_array(mean_m_l, 2);
     return Py_BuildValue("OOOO", mean_p_ndarray, mean_m_ndarray, mean_p_l_ndarray, mean_m_l_ndarray);
}


static PyObject *xrtm_flux_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     enum xrtm_solver_mask solver;
     const char *solver_string = NULL;
     npy_intp dims[2];
     PyObject *flux_p_ndarray = NULL;
     double *flux_p;
     PyObject *flux_m_ndarray = NULL;
     double *flux_m;
     PyObject *flux_p_l_ndarray = NULL;
     double **flux_p_l;
     PyObject *flux_m_l_ndarray = NULL;
     double **flux_m_l;
     if (! PyArg_ParseTuple(args, "s", &solver_string))
          return NULL;
     solver = xrtm_solver_name_to_mask(solver_string);
     if ((int) solver < 0) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solver_name_to_mask()");
          return NULL;
     }
     dims[0] = d->n_out_levels;
     flux_p_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_p_ndarray == NULL)
          return NULL;
     flux_p = (double *) array_from_ndarray(flux_p_ndarray, 8);
     dims[0] = d->n_out_levels;
     flux_m_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_m_ndarray == NULL)
          return NULL;
     flux_m = (double *) array_from_ndarray(flux_m_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_p_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_p_l_ndarray == NULL)
          return NULL;
     flux_p_l = (double **) array_from_ndarray(flux_p_l_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_m_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_m_l_ndarray == NULL)
          return NULL;
     flux_m_l = (double **) array_from_ndarray(flux_m_l_ndarray, 8);
     r = xrtm_flux(d, (enum xrtm_solver_mask) solver, flux_p, flux_m, flux_p_l, flux_m_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_flux()");
          return NULL;
     }
     free_array(flux_p_l, 2);
     free_array(flux_m_l, 2);
     return Py_BuildValue("OOOO", flux_p_ndarray, flux_m_ndarray, flux_p_l_ndarray, flux_m_l_ndarray);
}


static PyObject *xrtm_flux_divergence_py(xrtm_data_py *self, PyObject *args)
{
     int r;
     xrtm_data *d = &self->xrtm;
     enum xrtm_solver_mask solver;
     const char *solver_string = NULL;
     npy_intp dims[2];
     PyObject *flux_div_ndarray = NULL;
     double *flux_div;
     PyObject *flux_div_l_ndarray = NULL;
     double **flux_div_l;
     if (! PyArg_ParseTuple(args, "s", &solver_string))
          return NULL;
     solver = xrtm_solver_name_to_mask(solver_string);
     if ((int) solver < 0) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_solver_name_to_mask()");
          return NULL;
     }
     dims[0] = d->n_out_levels;
     flux_div_ndarray = PyArray_SimpleNew(1, dims, NPY_DOUBLE);
     if (flux_div_ndarray == NULL)
          return NULL;
     flux_div = (double *) array_from_ndarray(flux_div_ndarray, 8);
     dims[0] = d->n_out_levels;
     dims[1] = d->n_derivs;
     flux_div_l_ndarray = PyArray_SimpleNew(2, dims, NPY_DOUBLE);
     if (flux_div_l_ndarray == NULL)
          return NULL;
     flux_div_l = (double **) array_from_ndarray(flux_div_l_ndarray, 8);
     r = xrtm_flux_divergence(d, (enum xrtm_solver_mask) solver, flux_div, flux_div_l);
     if (r == XRTM_INT_ERROR) {
          PyErr_SetString(XRTMError, "ERROR: xrtm_flux_divergence()");
          return NULL;
     }
     free_array(flux_div_l, 2);
     return Py_BuildValue("OO", flux_div_ndarray, flux_div_l_ndarray);
}


static PyMethodDef xrtm_methods[] = {
     {"get_options", (PyCFunction) xrtm_get_options_py, METH_VARARGS, "null"},
     {"get_solvers", (PyCFunction) xrtm_get_solvers_py, METH_VARARGS, "null"},
     {"get_max_coef", (PyCFunction) xrtm_get_max_coef_py, METH_VARARGS, "null"},
     {"get_n_quad", (PyCFunction) xrtm_get_n_quad_py, METH_VARARGS, "null"},
     {"get_n_stokes", (PyCFunction) xrtm_get_n_stokes_py, METH_VARARGS, "null"},
     {"get_n_derivs", (PyCFunction) xrtm_get_n_derivs_py, METH_VARARGS, "null"},
     {"get_n_layers", (PyCFunction) xrtm_get_n_layers_py, METH_VARARGS, "null"},
     {"get_n_kernels", (PyCFunction) xrtm_get_n_kernels_py, METH_VARARGS, "null"},
     {"get_n_kernel_quad", (PyCFunction) xrtm_get_n_kernel_quad_py, METH_VARARGS, "null"},
     {"get_kernel", (PyCFunction) xrtm_get_kernel_py, METH_VARARGS, "null"},
     {"get_n_out_levels", (PyCFunction) xrtm_get_n_out_levels_py, METH_VARARGS, "null"},
     {"get_n_out_thetas", (PyCFunction) xrtm_get_n_out_thetas_py, METH_VARARGS, "null"},
     {"get_n_out_thetas_2", (PyCFunction) xrtm_get_n_out_thetas_2_py, METH_VARARGS, "null"},
     {"set_doub_d_tau", (PyCFunction) xrtm_set_doub_d_tau_py, METH_VARARGS, "null"},
     {"get_doub_d_tau", (PyCFunction) xrtm_get_doub_d_tau_py, METH_VARARGS, "null"},
     {"set_pade_params", (PyCFunction) xrtm_set_pade_params_py, METH_VARARGS, "null"},
     {"get_pade_params", (PyCFunction) xrtm_get_pade_params_py, METH_VARARGS, "null"},
     {"set_sos_params", (PyCFunction) xrtm_set_sos_params_py, METH_VARARGS, "null"},
     {"get_sos_params", (PyCFunction) xrtm_get_sos_params_py, METH_VARARGS, "null"},
     {"set_fourier_tol", (PyCFunction) xrtm_set_fourier_tol_py, METH_VARARGS, "null"},
     {"get_fourier_tol", (PyCFunction) xrtm_get_fourier_tol_py, METH_VARARGS, "null"},
     {"set_lambda", (PyCFunction) xrtm_set_lambda_py, METH_VARARGS, "null"},
     {"get_lambda", (PyCFunction) xrtm_get_lambda_py, METH_VARARGS, "null"},
     {"set_planet_r", (PyCFunction) xrtm_set_planet_r_py, METH_VARARGS, "null"},
     {"get_planet_r", (PyCFunction) xrtm_get_planet_r_py, METH_VARARGS, "null"},
     {"set_levels_z", (PyCFunction) xrtm_set_levels_z_py, METH_VARARGS, "null"},
     {"get_levels_z", (PyCFunction) xrtm_get_levels_z_py, METH_VARARGS, "null"},
     {"set_out_levels", (PyCFunction) xrtm_set_out_levels_py, METH_VARARGS, "null"},
     {"get_out_levels", (PyCFunction) xrtm_get_out_levels_py, METH_VARARGS, "null"},
     {"set_out_taus", (PyCFunction) xrtm_set_out_taus_py, METH_VARARGS, "null"},
     {"get_out_taus", (PyCFunction) xrtm_get_out_taus_py, METH_VARARGS, "null"},
     {"set_out_thetas", (PyCFunction) xrtm_set_out_thetas_py, METH_VARARGS, "null"},
     {"get_out_thetas", (PyCFunction) xrtm_get_out_thetas_py, METH_VARARGS, "null"},
     {"set_F_iso_top", (PyCFunction) xrtm_set_F_iso_top_py, METH_VARARGS, "null"},
     {"get_F_iso_top", (PyCFunction) xrtm_get_F_iso_top_py, METH_VARARGS, "null"},
     {"set_F_iso_top_l_1", (PyCFunction) xrtm_set_F_iso_top_l_1_py, METH_VARARGS, "null"},
     {"set_F_iso_top_l_n", (PyCFunction) xrtm_set_F_iso_top_l_n_py, METH_VARARGS, "null"},
     {"get_F_iso_top_l", (PyCFunction) xrtm_get_F_iso_top_l_py, METH_VARARGS, "null"},
     {"set_F_iso_bot", (PyCFunction) xrtm_set_F_iso_bot_py, METH_VARARGS, "null"},
     {"get_F_iso_bot", (PyCFunction) xrtm_get_F_iso_bot_py, METH_VARARGS, "null"},
     {"set_F_iso_bot_l_1", (PyCFunction) xrtm_set_F_iso_bot_l_1_py, METH_VARARGS, "null"},
     {"set_F_iso_bot_l_n", (PyCFunction) xrtm_set_F_iso_bot_l_n_py, METH_VARARGS, "null"},
     {"get_F_iso_bot_l", (PyCFunction) xrtm_get_F_iso_bot_l_py, METH_VARARGS, "null"},
     {"set_F_0", (PyCFunction) xrtm_set_F_0_py, METH_VARARGS, "null"},
     {"get_F_0", (PyCFunction) xrtm_get_F_0_py, METH_VARARGS, "null"},
     {"set_theta_0", (PyCFunction) xrtm_set_theta_0_py, METH_VARARGS, "null"},
     {"get_theta_0", (PyCFunction) xrtm_get_theta_0_py, METH_VARARGS, "null"},
     {"set_phi_0", (PyCFunction) xrtm_set_phi_0_py, METH_VARARGS, "null"},
     {"get_phi_0", (PyCFunction) xrtm_get_phi_0_py, METH_VARARGS, "null"},
     {"set_levels_b", (PyCFunction) xrtm_set_levels_b_py, METH_VARARGS, "null"},
     {"get_levels_b", (PyCFunction) xrtm_get_levels_b_py, METH_VARARGS, "null"},
     {"set_levels_b_l_1", (PyCFunction) xrtm_set_levels_b_l_1_py, METH_VARARGS, "null"},
     {"set_levels_b_l_n", (PyCFunction) xrtm_set_levels_b_l_n_py, METH_VARARGS, "null"},
     {"get_levels_b_l", (PyCFunction) xrtm_get_levels_b_l_py, METH_VARARGS, "null"},
     {"set_surface_b", (PyCFunction) xrtm_set_surface_b_py, METH_VARARGS, "null"},
     {"get_surface_b", (PyCFunction) xrtm_get_surface_b_py, METH_VARARGS, "null"},
     {"set_surface_b_l_1", (PyCFunction) xrtm_set_surface_b_l_1_py, METH_VARARGS, "null"},
     {"set_surface_b_l_n", (PyCFunction) xrtm_set_surface_b_l_n_py, METH_VARARGS, "null"},
     {"get_surface_b_l", (PyCFunction) xrtm_get_surface_b_l_py, METH_VARARGS, "null"},
     {"set_g_1", (PyCFunction) xrtm_set_g_1_py, METH_VARARGS, "null"},
     {"set_g_n", (PyCFunction) xrtm_set_g_n_py, METH_VARARGS, "null"},
     {"get_g", (PyCFunction) xrtm_get_g_py, METH_VARARGS, "null"},
     {"set_g_l_11", (PyCFunction) xrtm_set_g_l_11_py, METH_VARARGS, "null"},
     {"set_g_l_n1", (PyCFunction) xrtm_set_g_l_n1_py, METH_VARARGS, "null"},
     {"set_g_l_1n", (PyCFunction) xrtm_set_g_l_1n_py, METH_VARARGS, "null"},
     {"set_g_l_nn", (PyCFunction) xrtm_set_g_l_nn_py, METH_VARARGS, "null"},
     {"get_g_l", (PyCFunction) xrtm_get_g_l_py, METH_VARARGS, "null"},
     {"set_coef_1", (PyCFunction) xrtm_set_coef_1_py, METH_VARARGS, "null"},
     {"set_coef_n", (PyCFunction) xrtm_set_coef_n_py, METH_VARARGS, "null"},
     {"get_n_coef", (PyCFunction) xrtm_get_n_coef_py, METH_VARARGS, "null"},
     {"get_coef", (PyCFunction) xrtm_get_coef_py, METH_VARARGS, "null"},
     {"set_coef_l_11", (PyCFunction) xrtm_set_coef_l_11_py, METH_VARARGS, "null"},
     {"set_coef_l_n1", (PyCFunction) xrtm_set_coef_l_n1_py, METH_VARARGS, "null"},
     {"set_coef_l_1n", (PyCFunction) xrtm_set_coef_l_1n_py, METH_VARARGS, "null"},
     {"set_coef_l_nn", (PyCFunction) xrtm_set_coef_l_nn_py, METH_VARARGS, "null"},
     {"get_coef_l", (PyCFunction) xrtm_get_coef_l_py, METH_VARARGS, "null"},
     {"set_omega_1", (PyCFunction) xrtm_set_omega_1_py, METH_VARARGS, "null"},
     {"set_omega_n", (PyCFunction) xrtm_set_omega_n_py, METH_VARARGS, "null"},
     {"get_omega", (PyCFunction) xrtm_get_omega_py, METH_VARARGS, "null"},
     {"set_omega_l_11", (PyCFunction) xrtm_set_omega_l_11_py, METH_VARARGS, "null"},
     {"set_omega_l_n1", (PyCFunction) xrtm_set_omega_l_n1_py, METH_VARARGS, "null"},
     {"set_omega_l_1n", (PyCFunction) xrtm_set_omega_l_1n_py, METH_VARARGS, "null"},
     {"set_omega_l_nn", (PyCFunction) xrtm_set_omega_l_nn_py, METH_VARARGS, "null"},
     {"get_omega_l", (PyCFunction) xrtm_get_omega_l_py, METH_VARARGS, "null"},
     {"set_ltau_1", (PyCFunction) xrtm_set_ltau_1_py, METH_VARARGS, "null"},
     {"set_ltau_n", (PyCFunction) xrtm_set_ltau_n_py, METH_VARARGS, "null"},
     {"get_ltau", (PyCFunction) xrtm_get_ltau_py, METH_VARARGS, "null"},
     {"set_ltau_l_11", (PyCFunction) xrtm_set_ltau_l_11_py, METH_VARARGS, "null"},
     {"set_ltau_l_n1", (PyCFunction) xrtm_set_ltau_l_n1_py, METH_VARARGS, "null"},
     {"set_ltau_l_1n", (PyCFunction) xrtm_set_ltau_l_1n_py, METH_VARARGS, "null"},
     {"set_ltau_l_nn", (PyCFunction) xrtm_set_ltau_l_nn_py, METH_VARARGS, "null"},
     {"get_ltau_l", (PyCFunction) xrtm_get_ltau_l_py, METH_VARARGS, "null"},
     {"set_kernel_ampfac", (PyCFunction) xrtm_set_kernel_ampfac_py, METH_VARARGS, "null"},
     {"get_kernel_ampfac", (PyCFunction) xrtm_get_kernel_ampfac_py, METH_VARARGS, "null"},
     {"set_kernel_params_1", (PyCFunction) xrtm_set_kernel_params_1_py, METH_VARARGS, "null"},
     {"set_kernel_params_n", (PyCFunction) xrtm_set_kernel_params_n_py, METH_VARARGS, "null"},
     {"get_kernel_params", (PyCFunction) xrtm_get_kernel_params_py, METH_VARARGS, "null"},
     {"set_kernel_ampfac_l_1", (PyCFunction) xrtm_set_kernel_ampfac_l_1_py, METH_VARARGS, "null"},
     {"set_kernel_ampfac_l_n", (PyCFunction) xrtm_set_kernel_ampfac_l_n_py, METH_VARARGS, "null"},
     {"get_kernel_ampfac_l", (PyCFunction) xrtm_get_kernel_ampfac_l_py, METH_VARARGS, "null"},
     {"set_kernel_params_l_11", (PyCFunction) xrtm_set_kernel_params_l_11_py, METH_VARARGS, "null"},
     {"set_kernel_params_l_1n", (PyCFunction) xrtm_set_kernel_params_l_1n_py, METH_VARARGS, "null"},
     {"set_kernel_params_l_n1", (PyCFunction) xrtm_set_kernel_params_l_n1_py, METH_VARARGS, "null"},
     {"set_kernel_params_l_nn", (PyCFunction) xrtm_set_kernel_params_l_nn_py, METH_VARARGS, "null"},
     {"get_kernel_params_l", (PyCFunction) xrtm_get_kernel_params_l_py, METH_VARARGS, "null"},
     {"update_varied_layers", (PyCFunction) xrtm_update_varied_layers_py, METH_VARARGS, "null"},
     {"qx", (PyCFunction) xrtm_qx_py, METH_VARARGS, "null"},
     {"qw", (PyCFunction) xrtm_qw_py, METH_VARARGS, "null"},
     {"kernel_qx", (PyCFunction) xrtm_kernel_qx_py, METH_VARARGS, "null"},
     {"kernel_qw", (PyCFunction) xrtm_kernel_qw_py, METH_VARARGS, "null"},
     {"solution", (PyCFunction) xrtm_solution_py, METH_VARARGS, "null"},
     {"radiance", (PyCFunction) xrtm_radiance_py, METH_VARARGS, "null"},
     {"mean_radiance", (PyCFunction) xrtm_mean_radiance_py, METH_VARARGS, "null"},
     {"flux", (PyCFunction) xrtm_flux_py, METH_VARARGS, "null"},
     {"flux_divergence", (PyCFunction) xrtm_flux_divergence_py, METH_VARARGS, "null"},
     {NULL}
};




static PyMemberDef xrtm_members[] = {
     {NULL}
};


static PyTypeObject xrtm_type = {
#if PY_MAJOR_VERSION < 3
     PyObject_HEAD_INIT(NULL)
     0,
#else
     PyVarObject_HEAD_INIT(NULL, 0)
#endif
     "xrtm.xrtm",
     sizeof(xrtm_data_py),
     0,
     (destructor) xrtm_dealloc,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
     "XRTM object",
     0,
     0,
     0,
     0,
     0,
     0,
     xrtm_methods,
     xrtm_members,
     0,
     0,
     0,
     0,
     0,
     0,
     (initproc) xrtm_init,
     0,
     (newfunc) xrtm_new
};


static PyMethodDef module_methods[] = {
     {NULL}
};


#ifndef PyMODINIT_FUNC
#define PyMODINIT_FUNC void
#endif


#if PY_MAJOR_VERSION >= 3
    static struct PyModuleDef module_def = {
        PyModuleDef_HEAD_INIT,
        "xrtm",
        "Module for accessing XRTM",
        -1,
        module_methods,
        NULL,
        NULL,
        NULL,
        NULL
    };
#endif


#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initxrtm(void)
{
     PyObject *module;
     if (PyType_Ready(&xrtm_type) < 0)
          return;
     module = Py_InitModule3("xrtm", module_methods, "Module for accessing XRTM");
     if (module == NULL)
          return;
     Py_INCREF(&xrtm_type);
     PyModule_AddObject(module, "xrtm", (PyObject *) &xrtm_type);
     XRTMError = PyErr_NewException("xrtm.error", NULL, NULL);
     Py_INCREF(XRTMError);
     PyModule_AddObject(module, "error", XRTMError);
     import_array();
}
#else
PyMODINIT_FUNC PyInit_xrtm(void)
{
     PyObject *module;
     if (PyType_Ready(&xrtm_type) < 0)
          return NULL;
     module = PyModule_Create(&module_def);
     if (module == NULL)
          return NULL;
     Py_INCREF(&xrtm_type);
     PyModule_AddObject(module, "xrtm", (PyObject *) &xrtm_type);
     XRTMError = PyErr_NewException("xrtm.error", NULL, NULL);
     Py_INCREF(XRTMError);
     PyModule_AddObject(module, "error", XRTMError);
     import_array();
     return module;
}
#endif
