xrtm_adding.o: xrtm_adding.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_adding_a.h \
 prototypes/xrtm_adding_a_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_scatter.h prototypes/xrtm_scatter_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_adding2.c
xrtm_adding_a.o: xrtm_adding_a.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_adding_a.h \
 prototypes/xrtm_adding_a_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_scatter.h prototypes/xrtm_scatter_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_adding_a2.c
xrtm_brdf.o: xrtm_brdf.c xrtm.h ../src2/xrtm2.h xrtm_brdf.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_brdf_p.h xrtm_brdf_a.h \
 prototypes/xrtm_brdf_a_p.h xrtm_utility.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h prototypes/xrtm_utility_p.h
xrtm_brdf_a.o: xrtm_brdf_a.c xrtm.h ../src2/xrtm2.h xrtm_brdf.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_brdf_p.h \
 xrtm_brdf_a.h prototypes/xrtm_brdf_a_p.h xrtm_utility.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h prototypes/xrtm_utility_p.h
xrtm_derivs.o: xrtm_derivs.c xrtm_derivs.h prototypes/xrtm_derivs_p.h
xrtm_doub_rts.o: xrtm_doub_rts.c xrtm.h ../src2/xrtm2.h xrtm_doub_rts.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_doub_rts_p.h xrtm_doubling.h \
 prototypes/xrtm_doubling_p.h xrtm_scatter.h prototypes/xrtm_scatter_p.h \
 xrtm_source.h prototypes/xrtm_source_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_doub_rts2.c
xrtm_doubling.o: xrtm_doubling.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_doubling.h \
 prototypes/xrtm_doubling_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_scatter.h prototypes/xrtm_scatter_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_doubling2.c
xrtm_eig_bvp.o: xrtm_eig_bvp.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_eig_bvp.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_work.h prototypes/xrtm_work_p.h \
 prototypes/xrtm_eig_bvp_p.h xrtm_eig_bvp_a.h \
 prototypes/xrtm_eig_bvp_a_p.h xrtm_eig_util.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_sfi.h prototypes/xrtm_sfi_p.h xrtm_source.h \
 prototypes/xrtm_source_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 type_set.h xrtm_eig_bvp_x.c type_unset.h
xrtm_eig_bvp_a.o: xrtm_eig_bvp_a.c xrtm.h ../src2/xrtm2.h \
 xrtm_eig_bvp_a.h xrtm_save_tree.h prototypes/xrtm_save_tree_p.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_eig_bvp_a_p.h \
 xrtm_eig_util_a.h prototypes/xrtm_eig_util_a_p.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h xrtm_source_a.h prototypes/xrtm_source_a_p.h \
 xrtm_utility.h prototypes/xrtm_utility_p.h xrtm_utility_a.h \
 prototypes/xrtm_utility_a_p.h type_set.h xrtm_eig_bvp_x_a.c \
 ../src2/xrtm_eig_bvp_x_a2.c type_unset.h ../src2/xrtm_eig_bvp_a2.c
xrtm_eig_bvp_x.o: xrtm_eig_bvp_x.c
xrtm_eig_bvp_x_a.o: xrtm_eig_bvp_x_a.c ../src2/xrtm_eig_bvp_x_a2.c
xrtm_eig_rts.o: xrtm_eig_rts.c xrtm.h ../src2/xrtm2.h xrtm_eig_rts.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_eig_rts_p.h xrtm_eig_rts_a.h \
 prototypes/xrtm_eig_rts_a_p.h xrtm_eig_util.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_scatter.h prototypes/xrtm_scatter_p.h xrtm_source.h \
 prototypes/xrtm_source_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 type_set.h xrtm_eig_rts_x.c type_unset.h
xrtm_eig_rts_a.o: xrtm_eig_rts_a.c xrtm.h ../src2/xrtm2.h \
 xrtm_eig_rts_a.h xrtm_save_tree.h prototypes/xrtm_save_tree_p.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_eig_rts_a_p.h \
 xrtm_eig_util_a.h prototypes/xrtm_eig_util_a_p.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h xrtm_scatter_a.h \
 prototypes/xrtm_scatter_a_p.h xrtm_source_a.h \
 prototypes/xrtm_source_a_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 xrtm_utility_a.h prototypes/xrtm_utility_a_p.h type_set.h \
 xrtm_eig_rts_x_a.c ../src2/xrtm_eig_rts_x_a2.c type_unset.h \
 ../src2/xrtm_eig_rts_a2.c
xrtm_eig_rts_x.o: xrtm_eig_rts_x.c
xrtm_eig_rts_x_a.o: xrtm_eig_rts_x_a.c ../src2/xrtm_eig_rts_x_a2.c
xrtm_eig_util.o: xrtm_eig_util.c xrtm.h ../src2/xrtm2.h xrtm_eig_util.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h xrtm_eig_util_a.h \
 prototypes/xrtm_eig_util_a_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_utility.h prototypes/xrtm_utility_p.h ../src2/xrtm_eig_util2.c
xrtm_eig_util_a.o: xrtm_eig_util_a.c xrtm.h ../src2/xrtm2.h \
 xrtm_eig_util.h xrtm_save_tree.h prototypes/xrtm_save_tree_p.h \
 xrtm_work.h prototypes/xrtm_work_p.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h xrtm_eig_util_a.h \
 prototypes/xrtm_eig_util_a_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_utility.h prototypes/xrtm_utility_p.h ../src2/xrtm_eig_util_a2.c
xrtm_external.o: xrtm_external.c xrtm.h ../src2/xrtm2.h xrtm_brdf.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_brdf_p.h \
 xrtm_external.h prototypes/xrtm_external_p.h ../src2/xrtm_external2.c
xrtm_fd_interface.o: xrtm_fd_interface.c xrtm_fd_interface.h \
 xrtm_interface.h xrtm.h ../src2/xrtm2.h xrtm_brdf.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_brdf_p.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_stacks.h xrtm_adding.h \
 prototypes/xrtm_adding_p.h prototypes/xrtm_stacks_p.h version.h \
 ../src2/xrtm_interface2.h prototypes/xrtm_interface_p.h xrtm_model.h \
 prototypes/xrtm_model_p.h prototypes/xrtm_fd_interface_p.h \
 xrtm_support.h xrtm_eig_util.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h ../src2/xrtm_support2.h \
 prototypes/xrtm_support_p.h
xrtm_four_stream.o: xrtm_four_stream.c xrtm.h ../src2/xrtm2.h \
 xrtm_derivs.h prototypes/xrtm_derivs_p.h xrtm_four_stream.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_four_stream_p.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h xrtm_scatter.h prototypes/xrtm_scatter_p.h \
 xrtm_sfi.h prototypes/xrtm_sfi_p.h
xrtm_interface.o: xrtm_interface.c xrtm.h ../src2/xrtm2.h xrtm_brdf.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_brdf_p.h \
 xrtm_derivs.h prototypes/xrtm_derivs_p.h xrtm_interface.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_stacks.h \
 xrtm_adding.h prototypes/xrtm_adding_p.h prototypes/xrtm_stacks_p.h \
 version.h ../src2/xrtm_interface2.h prototypes/xrtm_interface_p.h \
 xrtm_model.h prototypes/xrtm_model_p.h xrtm_model_a.h \
 prototypes/xrtm_model_a_p.h xrtm_support.h xrtm_eig_util.h \
 ../src2/xrtm_eig_util2.h prototypes/xrtm_eig_util_p.h \
 ../src2/xrtm_support2.h prototypes/xrtm_support_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h xrtm_pade_rts.h prototypes/xrtm_pade_rts_p.h \
 ../src2/xrtm_interface2.c
xrtm_matrix.o: xrtm_matrix.c xrtm.h ../src2/xrtm2.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h ../src2/xrtm_matrix2.c
xrtm_mem_bvp.o: xrtm_mem_bvp.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_eig_util.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_work.h prototypes/xrtm_work_p.h \
 ../src2/xrtm_eig_util2.h prototypes/xrtm_eig_util_p.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h xrtm_mem_bvp.h prototypes/xrtm_mem_bvp_p.h \
 xrtm_source.h prototypes/xrtm_source_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h type_set.h xrtm_mem_bvp_x.c type_unset.h
xrtm_mem_bvp_x.o: xrtm_mem_bvp_x.c
xrtm_model.o: xrtm_model.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_brdf.h \
 prototypes/xrtm_brdf_p.h xrtm_derivs.h prototypes/xrtm_derivs_p.h \
 xrtm_doub_rts.h prototypes/xrtm_doub_rts_p.h xrtm_eig_bvp.h \
 prototypes/xrtm_eig_bvp_p.h xrtm_eig_rts.h prototypes/xrtm_eig_rts_p.h \
 xrtm_external.h prototypes/xrtm_external_p.h xrtm_four_stream.h \
 prototypes/xrtm_four_stream_p.h xrtm_interface.h xrtm_stacks.h \
 prototypes/xrtm_stacks_p.h version.h ../src2/xrtm_interface2.h \
 prototypes/xrtm_interface_p.h xrtm_mem_bvp.h prototypes/xrtm_mem_bvp_p.h \
 xrtm_model.h prototypes/xrtm_model_p.h xrtm_model_a.h \
 prototypes/xrtm_model_a_p.h xrtm_pade_rts.h prototypes/xrtm_pade_rts_p.h \
 xrtm_radiance.h prototypes/xrtm_radiance_p.h xrtm_single.h \
 prototypes/xrtm_single_p.h xrtm_scatter.h prototypes/xrtm_scatter_p.h \
 xrtm_scatter_a.h prototypes/xrtm_scatter_a_p.h xrtm_six_stream.h \
 prototypes/xrtm_six_stream_p.h xrtm_sos.h prototypes/xrtm_sos_p.h \
 xrtm_source.h prototypes/xrtm_source_p.h xrtm_support.h xrtm_eig_util.h \
 ../src2/xrtm_eig_util2.h prototypes/xrtm_eig_util_p.h \
 ../src2/xrtm_support2.h prototypes/xrtm_support_p.h xrtm_two_os.h \
 prototypes/xrtm_two_os_p.h xrtm_two_stream.h \
 prototypes/xrtm_two_stream_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_model2.c
xrtm_model_a.o: xrtm_model_a.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_adding_a.h \
 prototypes/xrtm_adding_a_p.h xrtm_brdf.h prototypes/xrtm_brdf_p.h \
 xrtm_brdf_a.h prototypes/xrtm_brdf_a_p.h xrtm_eig_bvp_a.h \
 prototypes/xrtm_eig_bvp_a_p.h xrtm_eig_rts_a.h \
 prototypes/xrtm_eig_rts_a_p.h xrtm_external.h \
 prototypes/xrtm_external_p.h xrtm_interface.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_stacks.h prototypes/xrtm_stacks_p.h \
 version.h ../src2/xrtm_interface2.h prototypes/xrtm_interface_p.h \
 xrtm_model.h prototypes/xrtm_model_p.h xrtm_model_a.h \
 prototypes/xrtm_model_a_p.h xrtm_radiance_a.h \
 prototypes/xrtm_radiance_a_p.h xrtm_single_a.h \
 prototypes/xrtm_single_a_p.h xrtm_scatter.h prototypes/xrtm_scatter_p.h \
 xrtm_scatter_a.h prototypes/xrtm_scatter_a_p.h xrtm_source_a.h \
 prototypes/xrtm_source_a_p.h xrtm_support.h xrtm_eig_util.h \
 ../src2/xrtm_eig_util2.h prototypes/xrtm_eig_util_p.h \
 ../src2/xrtm_support2.h prototypes/xrtm_support_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h xrtm_utility_a.h \
 prototypes/xrtm_utility_a_p.h ../src2/xrtm_model_a2.c
xrtm_pade_rts.o: xrtm_pade_rts.c xrtm.h ../src2/xrtm2.h xrtm_doubling.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_doubling_p.h xrtm_matrix.h \
 prototypes/xrtm_matrix_p.h xrtm_pade_rts.h prototypes/xrtm_pade_rts_p.h \
 xrtm_scatter.h prototypes/xrtm_scatter_p.h xrtm_source.h \
 prototypes/xrtm_source_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 pade_table.h pade_table_l.h ../src2/xrtm_pade_rts2.c
xrtm_radiance.o: xrtm_radiance.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_radiance.h \
 prototypes/xrtm_radiance_p.h xrtm_radiance_a.h \
 prototypes/xrtm_radiance_a_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_radiance2.c
xrtm_radiance_a.o: xrtm_radiance_a.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_radiance_a.h \
 prototypes/xrtm_radiance_a_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_radiance_a2.c
xrtm_save_tree.o: xrtm_save_tree.c xrtm.h ../src2/xrtm2.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h
xrtm_scatter.o: xrtm_scatter.c xrtm.h ../src2/xrtm2.h xrtm_scatter.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_scatter_p.h xrtm_scatter_a.h \
 prototypes/xrtm_scatter_a_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 ../src2/xrtm_scatter2.c
xrtm_scatter_a.o: xrtm_scatter_a.c xrtm.h ../src2/xrtm2.h xrtm_scatter.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_scatter_p.h xrtm_scatter_a.h \
 prototypes/xrtm_scatter_a_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 ../src2/xrtm_scatter_a2.c
xrtm_sfi.o: xrtm_sfi.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_utility.h xrtm_save_tree.h prototypes/xrtm_save_tree_p.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_utility_p.h \
 type_set.h xrtm_sfi_x.c sfi_block.h type_unset.h
xrtm_sfi_x.o: xrtm_sfi_x.c sfi_block.h
xrtm_single.o: xrtm_single.c xrtm.h ../src2/xrtm2.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_single.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_single_p.h xrtm_single_a.h \
 prototypes/xrtm_single_a_p.h xrtm_utility.h prototypes/xrtm_utility_p.h
xrtm_single_a.o: xrtm_single_a.c xrtm.h ../src2/xrtm2.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_single_a.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_single_a_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_single_a2.c
xrtm_six_stream.o: xrtm_six_stream.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_matrix.h prototypes/xrtm_matrix_p.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_scatter.h \
 xrtm_work.h prototypes/xrtm_work_p.h prototypes/xrtm_scatter_p.h \
 xrtm_six_stream.h prototypes/xrtm_six_stream_p.h xrtm_sfi.h \
 prototypes/xrtm_sfi_p.h
xrtm_sos.o: xrtm_sos.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_sos.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_work.h prototypes/xrtm_work_p.h \
 prototypes/xrtm_sos_p.h
xrtm_source.o: xrtm_source.c xrtm.h ../src2/xrtm2.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_source.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_source_p.h xrtm_source_a.h \
 prototypes/xrtm_source_a_p.h xrtm_utility.h prototypes/xrtm_utility_p.h \
 type_set.h xrtm_source_x.c type_unset.h
xrtm_source_a.o: xrtm_source_a.c xrtm.h ../src2/xrtm2.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_source_a.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_source_a_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h ../src2/xrtm_source_a2.c
xrtm_source_x.o: xrtm_source_x.c
xrtm_stacks.o: xrtm_stacks.c xrtm_stacks.h xrtm_adding.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_work.h prototypes/xrtm_work_p.h \
 prototypes/xrtm_adding_p.h prototypes/xrtm_stacks_p.h xrtm_support.h \
 xrtm.h ../src2/xrtm2.h xrtm_brdf.h prototypes/xrtm_brdf_p.h xrtm_model.h \
 xrtm_interface.h xrtm_derivs.h prototypes/xrtm_derivs_p.h version.h \
 ../src2/xrtm_interface2.h prototypes/xrtm_interface_p.h \
 prototypes/xrtm_model_p.h xrtm_eig_util.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h ../src2/xrtm_support2.h \
 prototypes/xrtm_support_p.h xrtm_utility.h prototypes/xrtm_utility_p.h
xrtm_support.o: xrtm_support.c xrtm_support.h xrtm.h ../src2/xrtm2.h \
 xrtm_brdf.h xrtm_work.h prototypes/xrtm_work_p.h \
 prototypes/xrtm_brdf_p.h xrtm_model.h xrtm_interface.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_stacks.h xrtm_adding.h \
 prototypes/xrtm_adding_p.h prototypes/xrtm_stacks_p.h version.h \
 ../src2/xrtm_interface2.h prototypes/xrtm_interface_p.h \
 prototypes/xrtm_model_p.h xrtm_eig_util.h ../src2/xrtm_eig_util2.h \
 prototypes/xrtm_eig_util_p.h ../src2/xrtm_support2.h \
 prototypes/xrtm_support_p.h ../src2/xrtm_support2.c
xrtm_two_os.o: xrtm_two_os.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_sos.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_work.h prototypes/xrtm_work_p.h \
 prototypes/xrtm_sos_p.h xrtm_two_os.h prototypes/xrtm_two_os_p.h \
 xrtm_utility.h prototypes/xrtm_utility_p.h
xrtm_two_stream.o: xrtm_two_stream.c xrtm.h ../src2/xrtm2.h xrtm_derivs.h \
 prototypes/xrtm_derivs_p.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h xrtm_two_stream.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_two_stream_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h
xrtm_utility.o: xrtm_utility.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h xrtm_utility_a.h \
 prototypes/xrtm_utility_a_p.h
xrtm_utility_a.o: xrtm_utility_a.c xrtm.h ../src2/xrtm2.h xrtm_adding.h \
 xrtm_save_tree.h prototypes/xrtm_save_tree_p.h xrtm_work.h \
 prototypes/xrtm_work_p.h prototypes/xrtm_adding_p.h xrtm_utility.h \
 prototypes/xrtm_utility_p.h xrtm_utility_a.h \
 prototypes/xrtm_utility_a_p.h ../src2/xrtm_utility_a2.c
xrtm_work.o: xrtm_work.c xrtm.h ../src2/xrtm2.h xrtm_work.h \
 prototypes/xrtm_work_p.h xrtm_utility.h xrtm_save_tree.h \
 prototypes/xrtm_save_tree_p.h prototypes/xrtm_utility_p.h
