     if (n_derivs == 0) {
          if (! solar) {
               if (! thermal || i_four > 0)
                    SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], NULL, ltau[i], NULL,NULL,       NULL, btran[i], NULL, as_0[i], NULL, atran[i], NULL, P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, B, NULL, I_0, NULL, offset2, I_u2, NULL, add_single_scattering, greens, solar, thermal, NULL, NULL, NULL, work, flag);
               else
                    SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], NULL, ltau[i], NULL,p_d_tau[i], NULL, btran[i], NULL, as_0[i], NULL, atran[i], NULL, P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, B, NULL, I_0, NULL, offset2, I_u2, NULL, add_single_scattering, greens, solar, thermal, NULL, NULL, NULL, work, flag);
          }
          else {
               if (! thermal || i_four > 0)
                    SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], NULL, ltau[i], NULL,NULL,       NULL, btran[i], NULL, as_0[i], NULL, atran[i], NULL, P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, B, NULL, I_0, NULL, offset2, I_u2, NULL, add_single_scattering, greens, solar, thermal, NULL, NULL, NULL, work, flag);
               else
                    SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], NULL, ltau[i], NULL,p_d_tau[i], NULL, btran[i], NULL, as_0[i], NULL, atran[i], NULL, P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, B, NULL, I_0, NULL, offset2, I_u2, NULL, add_single_scattering, greens, solar, thermal, NULL, NULL, NULL, work, flag);
          }
     }
     else {
          if (! flags_or2(derivs->layers, n_layers, n_derivs)) {
               if (! solar) {
                    if (! thermal || i_four > 0)
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], NULL,       NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], NULL,            NULL,               work, flag);
                    else if (! flags_or2(derivs->thermal, n_layers, n_derivs))
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], NULL,            derivs->thermal[i], work, flag);
                    else
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], p_d_tau_l[i], btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     At_p_l[i], At_m_l[i], B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], NULL,            derivs->thermal[i], work, flag);
               }
               else {
                    if (! thermal || i_four > 0)
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], NULL,       NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], derivs->beam[i], NULL,               work, flag);
                    else if (! flags_or2(derivs->thermal, n_layers, n_derivs))
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], derivs->beam[i], derivs->thermal[i], work, flag);
                    else
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], p_d_tau_l[i], btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL,         NULL,         NULL,         NULL,    NULL,     NULL,     NULL,     NULL,     At_p_l[i], At_m_l[i], B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], derivs->beam[i], derivs->thermal[i], work, flag);
               }
          }
          else {
               if (! solar) {
                    if (! thermal || i_four > 0)
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], NULL,       NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    NULL,         P_uq_pp_l[i], P_uq_mp_l[i], nu_l[i], X_p_l[i], X_m_l[i], NULL,     NULL,     NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], NULL,            NULL,               work, flag);
                    else
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], p_d_tau_l[i], btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, NULL,       P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], NULL,   NULL,   At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], NULL,         P_uq_pp_l[i], P_uq_mp_l[i], nu_l[i], X_p_l[i], X_m_l[i], NULL,     NULL,     At_p_l[i], At_m_l[i], B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], NULL,            derivs->thermal[i], work, flag);
               }
               else {
                    if (! thermal || i_four > 0)
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], NULL,       NULL,         btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], NULL,    NULL,    NULL,    NULL,    NULL,    NULL,    P_u0_pm_l[i], P_uq_pp_l[i], P_uq_mp_l[i], nu_l[i], X_p_l[i], X_m_l[i], F_p_l[i], F_m_l[i], NULL,      NULL,      B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], derivs->beam[i], NULL,               work, flag);
                    else
                         SFI_LAYER(i, ptau, i_four, n_quad, n_stokes, n_derivs, n_umus, qf, qx_v, qw_v, F_0, umus, omega[i], omega_l[i], ltau[i], ltau_l[i], p_d_tau[i], p_d_tau_l[i], btran[i], btran_l[i], as_0[i], as_0_l[i], atran[i], atran_l[i], P_q0_mm2, P_q0_pm2, P_u0_pm[i], P_uq_pp[i], P_uq_mp[i], nu[i], X_p[i], X_m[i], F_p[i], F_m[i], At_p[i], At_m[i], F0_p[i], F0_m[i], F1_p[i], F1_m[i], P_u0_pm_l[i], P_uq_pp_l[i], P_uq_mp_l[i], nu_l[i], X_p_l[i], X_m_l[i], F_p_l[i], F_m_l[i], At_p_l[i], At_m_l[i], B, B_l,  I_0, I_0_l, offset2, I_u2, I_u_l2, add_single_scattering, greens, solar, thermal, derivs->layers[i], derivs->beam[i], derivs->thermal[i], work, flag);
               }
          }
     }
