#undef xvec_zero
#undef xvec_copy
#undef xvec_print
#undef xvec_scale
#undef xvec_add 
#undef xvec_sub 
#undef xvec_lincmb
#undef xvec_dot
#undef xvec_mag 
#undef xvec_unit
#undef xvec_cross
#undef xvec_dyadic
#undef xvec_inv

#undef xmat_zero
#undef xmat_init
#undef xmat_copy
#undef xmat_print
#undef xmat_trans
#undef xmat_p_one_norm
#undef xmat_p_inf_norm
#undef xmat_frob_norm
#undef xmat_add
#undef xmat_add_diag
#undef xmat_add_trans
#undef xmat_sub
#undef xmat_sub_diag
#undef xmat_diag_sub
#undef xmat_sub_trans
#undef xmat_i_sub
#undef xmat_scale
#undef xm_v_mul
#undef xv_m_mul
#undef xm_v_diag_mul
#undef xm_v_dinv_mul
#undef xmat_mul
#undef xmat_gxgxmx
#undef xmat_mul_diag
#undef xmat_gxdxmx
#undef xmat_mul_dinv
#undef xmat_diag_mul
#undef xmat_dinv_mul
#undef xmat_pow_count
#undef xmat_pow

#undef xmat_pocon
#undef xmat_gecon
#undef xmat_potrf
#undef xmat_potri
#undef xmat_potrs
#undef xmat_getrf
#undef xmat_getri
#undef xmat_getrs
#undef xmat_getrs2
#undef xmat_gttrf
#undef xmat_gttrs

#undef xgbtrf_
#undef xgbtrs_

#undef get_work_x1
#undef get_work_x2
#undef get_work_x3

#undef copy_to_band_storage_x
#undef copy_to_band_storage2_x
